import {listCourses,originalDefinition} from '@/lib/courses';
import {identity} from '@/lib/student-session';
import {database} from '@/lib/database';
import {grades} from '@/lib/grades';
import {CHORES_COURSE_ID} from '@/lib/chores-learning';
import {ensureClassroomResults} from '@/lib/classroom-results';
import {gameSnapshot,BALLOON_POINTS} from '@/lib/balloon-assessment';
import {dictationSnapshot,DICTATION_POINTS} from '@/lib/chores-dictation';
export const dynamic='force-dynamic';
export async function GET(req:Request){try{await ensureClassroomResults();const grade=new URL(req.url).searchParams.get('grade');if(grade&&!grades.some(g=>g.id===grade))return Response.json({error:'صف غير صالح.'},{status:400});const all=await listCourses();const selected=grade?all.filter(c=>(c.grade||'general')===grade):all;const courses=await Promise.all(selected.map(async c=>{const id=await identity(req,c.id);let progress=null;if(id){const row=await database().prepare('SELECT s.name,s.completed,s.snapshot,COALESCE((SELECT attempt FROM student_sessions WHERE student=s.id),1) AS attempt,(SELECT COUNT(*) FROM answers a WHERE a.student=s.id) AS answered,(SELECT COALESCE(SUM(a.correct),0) FROM answers a WHERE a.student=s.id) AS score,(SELECT COUNT(*) FROM reads r WHERE r.student=s.id) AS reads FROM students s WHERE s.id=? AND s.course=?').bind(id,c.id).first<any>();if(row){const definition=row.snapshot?JSON.parse(row.snapshot).definition:c.id==='life-stories'?originalDefinition:c.definition;const questions=definition.questions.length,lessons=definition.lessons.length;const [game,dictation]=c.id===CHORES_COURSE_ID?await Promise.all([gameSnapshot(id,row.attempt),dictationSnapshot(id,row.attempt)]):[null,null],gameSolved=game?.gameBest?BALLOON_POINTS:game?.game?.solved||0,gameScore=game?.gameBest?.score||0,dictationScore=dictation?.answers.reduce((n,a)=>n+a.correct,0)||0;progress={name:row.name,answered:row.answered,score:row.score,reads:row.reads,questions,lessons,completed:c.id===CHORES_COURSE_ID&&(!game?.gameBest||!dictation?.completed)?null:row.completed,...(game?{gameScore,gameTotal:BALLOON_POINTS,dictationScore,dictationTotal:DICTATION_POINTS,totalScore:row.score+dictationScore+gameScore,totalPoints:questions+DICTATION_POINTS+BALLOON_POINTS}:{}),percent:Math.round((row.answered+row.reads+(dictation?.answers.length||0)+gameSolved)/(questions+lessons+(game?BALLOON_POINTS+DICTATION_POINTS:0))*100)};}}return {id:c.id,grade:c.grade||'general',title:c.title,description:c.description,lessons:c.definition.lessons.length,questions:c.definition.questions.length,...(c.id===CHORES_COURSE_ID?{gameRequired:true,gameTotal:BALLOON_POINTS,dictationTotal:DICTATION_POINTS}:{}),progress};}));
return Response.json({courses,grades:grades.map(g=>({...g,courses:all.filter(c=>(c.grade||'general')===g.id).length}))},{headers:{'Cache-Control':'no-store'}});}catch(e){console.error(e);return Response.json({error:'تعذّر تحميل الصفوف والتقدم. حاول مرة أخرى.'},{status:503,headers:{'Cache-Control':'no-store'}});}}
