'use client';
import {useEffect,useState} from 'react';
import {Plus,Trash2} from 'lucide-react';
import {MAX_COMMENT_OPTIONS,isNumberTask,validateCommentChoices,type CommentChoice,type RecordTask} from '@/lib/records';
type TaskSettingsValue=Pick<RecordTask,'type'|'maxScore'|'mode'|'positiveLabel'|'negativeLabel'|'choices'>;
const blankComments=():CommentChoice[]=>[{id:crypto.randomUUID(),label:'',tone:'positive'},{id:crypto.randomUUID(),label:'',tone:'negative'}];
function CommentSettings({choices,onChange}:{choices:CommentChoice[]|undefined;onChange:(patch:Partial<RecordTask>)=>void}){
  const serialized=JSON.stringify(choices||[]);
  const [draft,setDraft]=useState<CommentChoice[]>(()=>choices?.length?structuredClone(choices):blankComments()),[error,setError]=useState('');
  useEffect(()=>{const approved=JSON.parse(serialized) as CommentChoice[];setDraft(approved.length?approved:blankComments());setError('');},[serialized]);
  const pending=JSON.stringify(draft)!==serialized;
  function apply(){try{const approved=validateCommentChoices(draft);setError('');onChange({choices:approved});}catch(e){setError((e as Error).message);}}
  return <fieldset className="comment-options-editor"><legend>التعليقات التي تظهر في قائمة الرصد</legend><p className="field-help">اكتب التعليقات التي تناسبك، مثل حاضر أو غائب أو متأخر. اختر لون كل تعليق ثم اعتمد القائمة.</p><div className="comment-option-rows">{draft.map((choice,index)=><div className="comment-option-row" key={choice.id}><span>{index+1}</span><label>نص التعليق<input maxLength={120} aria-label={'نص التعليق '+(index+1)} value={choice.label} placeholder={index===0?'مثال: حاضر':'مثال: غائب أو متأخر'} onChange={e=>setDraft(current=>current.map(item=>item.id===choice.id?{...item,label:e.target.value}:item))}/></label><label className="comment-option-color">لون التعليق<select aria-label={'لون التعليق '+(index+1)} value={choice.tone} onChange={e=>setDraft(current=>current.map(item=>item.id===choice.id?{...item,tone:e.target.value as CommentChoice['tone']}:item))}><option value="positive">أخضر</option><option value="negative">أحمر</option><option value="neutral">ذهبي</option></select></label><button className="remove" type="button" disabled={draft.length===1} aria-label={'إزالة التعليق '+(index+1)} onClick={()=>setDraft(current=>current.filter(item=>item.id!==choice.id))}><Trash2 size={17}/></button></div>)}</div>{error&&<p className="comment-options-error" role="alert">{error}</p>}<div className="comment-option-actions"><button className="secondary compact" type="button" disabled={draft.length>=MAX_COMMENT_OPTIONS} onClick={()=>setDraft(current=>[...current,{id:crypto.randomUUID(),label:'',tone:'neutral'}])}><Plus size={15}/>إضافة تعليق</button><button className="primary compact" type="button" disabled={!pending} onClick={apply}>اعتماد التعليقات</button><span role="status">{pending?'اضغط اعتماد التعليقات لتظهر في قائمة الرصد.':'التعليقات معتمدة.'}</span></div></fieldset>;
}
export default function TaskSettings({task,onChange}:{task:TaskSettingsValue;onChange:(patch:Partial<RecordTask>)=>void}){
  if(task.type!=='custom'&&!isNumberTask(task))return null;
  return <div className="custom-task-settings">{task.type==='custom'&&<><label>طريقة الرصد<select value={task.mode||'status'} onChange={e=>{const mode=e.target.value as RecordTask['mode'];onChange(mode==='comments'?{mode,choices:[{id:crypto.randomUUID(),label:task.positiveLabel||'أنجز',tone:'positive'},{id:crypto.randomUUID(),label:task.negativeLabel||'لم ينجز',tone:'negative'}]}:{mode});}}><option value="comments">تعليقات أكتبها بنفسي</option><option value="status">تعليق عند الإتمام وتعليق عند عدم الإتمام</option><option value="check">علامة صح مع تعليق</option><option value="number">إدخال رقم</option></select></label>{task.mode==='comments'?<CommentSettings choices={task.choices} onChange={onChange}/>:task.mode!=='number'&&<><label>تعليق عند الإتمام / الصح<input required maxLength={60} value={task.positiveLabel??'أنجز'} onChange={e=>onChange({positiveLabel:e.target.value})}/></label><label>تعليق عند عدم الإتمام<input required maxLength={60} value={task.negativeLabel??'لم ينجز'} onChange={e=>onChange({negativeLabel:e.target.value})}/></label></>}</>}{isNumberTask(task)&&<label className="task-max-score">الدرجة الكاملة<input required type="number" min={0.01} max={1000} step="any" value={task.maxScore} onChange={e=>onChange({maxScore:Number(e.target.value)})}/><span className="score-presets"><button type="button" onClick={()=>onChange({maxScore:10})}>10</button><button type="button" onClick={()=>onChange({maxScore:20})}>20</button></span></label>}</div>;
}
