'use client';
import {useState,useEffect} from 'react';
import {BookOpen,Plus,Save,Share2,GraduationCap,Trash2,CheckCircle2,Download} from 'lucide-react';
import {grades,gradeLabel} from '@/lib/grades';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
import type {TeacherCourse,Lesson,QuizQuestion} from '@/lib/course-types';
const newLesson=():Lesson=>({title:'',en:'',tag:'01',intro:'',formula:'',rules:[['شرح القاعدة','','']],note:'',example:'',translation:''});
const newQuestion=(lesson:number):QuizQuestion=>({id:0,lesson,prompt:'',options:['','',''],answer:0,reason:''});
const fresh=():TeacherCourse=>({id:'',grade:'general',title:'',description:'',published:0,updated:'',definition:{lessons:[newLesson()],questions:[newQuestion(0)]}});
export default function TeacherDashboard({username}:{username:string}){const [courses,setCourses]=useState<TeacherCourse[]>([]),[draft,setDraft]=useState<TeacherCourse|null>(null),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''),[active,setActive]=useState(0);
async function load(){setLoading(true);setError('');try{const r=await fetch('/api/teacher');const d=await r.json() as {courses:TeacherCourse[];error:string};if(!r.ok)throw new Error(d.error);setCourses(d.courses);}catch(e){setError((e as Error).message);}finally{setLoading(false);}}useEffect(()=>{void load();},[]);
function update(fn:(d:TeacherCourse)=>void){setDraft(current=>{if(!current)return current;const next=structuredClone(current);fn(next);return next;});setNotice('');}
function edit(c:TeacherCourse){setDraft(structuredClone(c));setActive(0);setError('');setNotice('');}
function addLesson(){update(d=>{d.definition.lessons.push(newLesson());d.definition.questions.push(newQuestion(d.definition.lessons.length-1));});setActive(draft?.definition.lessons.length||0);}
function removeLesson(i:number){update(d=>{d.definition.lessons.splice(i,1);d.definition.questions=d.definition.questions.filter(q=>q.lesson!==i).map(q=>({...q,lesson:q.lesson>i?q.lesson-1:q.lesson}));});setActive(Math.max(0,i-1));}
async function save(published:number){if(!draft)return;setBusy(true);setError('');setNotice('');try{const r=await fetch('/api/teacher',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...draft,id:draft.id||undefined,published})});const d=await r.json() as {id:string;courses:TeacherCourse[];error:string};if(!r.ok)throw new Error(d.error);setCourses(d.courses);setDraft(d.courses.find(c=>c.id===d.id)||null);setNotice(published?'تم نشر الدرس. يمكنك نسخ رابطه وإرساله للطلاب.':'تم حفظ الدرس كمسودة. لا يظهر للطلاب حاليًا.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
async function copy(id:string){const url=new URL('/?course='+encodeURIComponent(id),window.location.origin).href;try{await navigator.clipboard.writeText(url);setNotice('تم نسخ رابط الدرس.');}catch{setNotice('رابط الدرس: '+url);}}
async function logout(){setBusy(true);setError('');try{const response=await fetch('/api/teacher/auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'logout'})});if(!response.ok)throw new Error('تعذر تسجيل الخروج.');window.location.replace('/teacher');}catch(e){setError((e as Error).message);setBusy(false);}}
const lesson=draft?.definition.lessons[active];return <div dir="rtl"><header className="topbar"><a className="brand" href="/"><span className="brand-mark">A<span>✦</span></span><span className="wordmark">ALWADANI<small>LEARNING STUDIO</small></span></a><div className="teacher-nav"><a className="secondary" href="/">عرض صفحة الطلاب</a><span className="teacher-account-name">حسابك: {username}</span><button className="teacher-signout" disabled={busy} onClick={logout}>تسجيل الخروج</button></div></header><main><div className="page-heading"><div><div className="eyebrow">TEACHER WORKSPACE</div><h1>دروسك، بطريقتك<span>.</span></h1><p>أضف الدروس وشارك روابطها. الطلاب يحتاجون أسماءهم فقط للبدء.</p></div><button className="primary" onClick={()=>edit(fresh())}><Plus size={18}/>إضافة درس</button></div>{error&&<div className="error-banner" role="alert">{error}</div>}{notice&&<div className="teacher-notice" role="status"><CheckCircle2 size={19}/>{notice}</div>}
{draft&&lesson?<section className="standalone teacher-editor"><div className="editor-heading"><h2>{draft.id?'تعديل الدرس':'درس جديد'}</h2><button className="secondary" onClick={()=>setDraft(null)} disabled={busy}>العودة إلى دروسي</button></div><fieldset disabled={busy}><div className="grade-field"><label htmlFor="course-grade">الصف الدراسي</label><Select dir="rtl" value={draft.grade||'general'} onValueChange={value=>update(d=>{d.grade=value;})}><SelectTrigger id="course-grade" className="grade-select"><SelectValue/></SelectTrigger><SelectContent>{grades.map(g=><SelectItem key={g.id} value={g.id}>{g.label}</SelectItem>)}</SelectContent></Select><p>يظهر الدرس المنشور داخل خانة الصف الذي تختاره.</p></div><div className="form-grid"><label>عنوان الدرس<input value={draft.title} maxLength={120} onChange={e=>update(d=>{d.title=e.target.value;})} placeholder="مثال: المضارع البسيط"/></label><label>وصف مختصر<input value={draft.description} maxLength={500} onChange={e=>update(d=>{d.description=e.target.value;})} placeholder="ماذا سيتعلم الطالب؟"/></label></div><div className="editor-divider"><h3>محطات الشرح والتدريب</h3><button className="secondary" onClick={addLesson}><Plus size={17}/>إضافة محطة</button></div><div className="editor-stations">{draft.definition.lessons.map((l,i)=><button key={i} className={i===active?'selected':''} onClick={()=>setActive(i)}>{i+1}. {l.title||'محطة جديدة'}</button>)}</div><div className="station-heading"><h3>المحطة {active+1}</h3>{draft.definition.lessons.length>1&&<button className="remove" onClick={()=>removeLesson(active)}><Trash2 size={15}/>حذف المحطة</button>}</div><div className="form-grid"><label>عنوان المحطة<input value={lesson.title} onChange={e=>update(d=>{d.definition.lessons[active].title=e.target.value;})}/></label><label>عنوان بالإنجليزية (اختياري)<input dir="ltr" value={lesson.en} onChange={e=>update(d=>{d.definition.lessons[active].en=e.target.value;})}/></label></div><label className="field">شرح تمهيدي<textarea value={lesson.intro} rows={3} onChange={e=>update(d=>{d.definition.lessons[active].intro=e.target.value;})}/></label><label className="field">تركيب الجملة (اختياري)<input dir="ltr" value={lesson.formula} onChange={e=>update(d=>{d.definition.lessons[active].formula=e.target.value;})} placeholder="Subject + verb"/></label>
{lesson.rules.map((r,i)=><div className="rule-editor" key={i}><div className="station-heading"><strong>فقرة شرح {i+1}</strong><button className="remove" onClick={()=>update(d=>{d.definition.lessons[active].rules.splice(i,1);})}>حذف الفقرة</button></div><label className="field">عنوان الفقرة<input value={r[0]} onChange={e=>update(d=>{d.definition.lessons[active].rules[i][0]=e.target.value;})}/></label><label className="field">الشرح<textarea rows={3} value={r[1]} onChange={e=>update(d=>{d.definition.lessons[active].rules[i][1]=e.target.value;})}/></label><label className="field">مثال بالإنجليزية<input dir="ltr" value={r[2]} onChange={e=>update(d=>{d.definition.lessons[active].rules[i][2]=e.target.value;})}/></label></div>)}<button className="secondary" onClick={()=>update(d=>{d.definition.lessons[active].rules.push(['','','']);})}><Plus size={16}/>إضافة فقرة شرح</button><div className="form-grid bottom-space"><label>مثال ختامي<input dir="ltr" value={lesson.example} onChange={e=>update(d=>{d.definition.lessons[active].example=e.target.value;})}/></label><label>ترجمته بالعربية<input value={lesson.translation} onChange={e=>update(d=>{d.definition.lessons[active].translation=e.target.value;})}/></label></div><label className="field">ملاحظة مهمة (اختيارية)<textarea rows={2} value={lesson.note} onChange={e=>update(d=>{d.definition.lessons[active].note=e.target.value;})}/></label>
<div className="editor-divider"><h3>تمارين المحطة</h3><button className="secondary" onClick={()=>update(d=>{d.definition.questions.push(newQuestion(active));})}><Plus size={16}/>إضافة سؤال</button></div><p className="field-help">حدد الإجابة الصحيحة، واكتب سببها ليظهر للطالب بعد الحل. يمكن كتابة ___ مكان الفراغ.</p>
{draft.definition.questions.map((q,index)=>q.lesson===active&&<div className="question-editor" key={index}><div className="station-heading"><strong>سؤال {draft.definition.questions.filter((x,i)=>x.lesson===active&&i<=index).length}</strong><button className="remove" onClick={()=>update(d=>{d.definition.questions.splice(index,1);})}>حذف السؤال</button></div><label className="field">نص السؤال<textarea dir="auto" rows={2} value={q.prompt} onChange={e=>update(d=>{d.definition.questions[index].prompt=e.target.value;})}/></label><span className="field-label">خيارات الإجابة — اختر الدائرة بجانب الإجابة الصحيحة</span><RadioGroup value={String(q.answer)} onValueChange={v=>update(d=>{d.definition.questions[index].answer=Number(v);})} className="teacher-options">{q.options.map((o,i)=><div key={i} className="teacher-option"><RadioGroupItem aria-label={`اجعل الخيار ${i+1} هو الإجابة الصحيحة`} value={String(i)}/><input aria-label={`الخيار ${i+1}`} dir="auto" value={o} onChange={e=>update(d=>{d.definition.questions[index].options[i]=e.target.value;})}/>{q.options.length>2&&<button aria-label={`حذف الخيار ${i+1}`} className="remove" onClick={()=>update(d=>{const q=d.definition.questions[index];q.options.splice(i,1);q.answer=q.answer===i?0:q.answer>i?q.answer-1:q.answer;})}><Trash2 size={16}/></button>}</div>)}</RadioGroup>{q.options.length<6&&<button className="secondary compact" onClick={()=>update(d=>{d.definition.questions[index].options.push('');})}>إضافة خيار</button>}<label className="field">سبب الإجابة الصحيحة<textarea rows={3} value={q.reason} onChange={e=>update(d=>{d.definition.questions[index].reason=e.target.value;})} placeholder="اشرح القاعدة وسبب اختيار هذه الإجابة."/></label></div>)}
</fieldset><div className="editor-save"><p>الطلاب الذين بدأوا الحل يحتفظون بنسخة درسهم ونتائجهم حتى بعد تعديل المحتوى.</p><div><button className="secondary" disabled={busy} onClick={()=>save(0)}><Save size={17}/>حفظ مسودة</button><button className="primary" disabled={busy} onClick={()=>save(1)}>{busy?'جارٍ الحفظ…':'حفظ ونشر للطلاب'}</button>{draft.id&&draft.published===1&&<button className="secondary" onClick={()=>copy(draft.id)}><Share2 size={17}/>نسخ رابط الدرس</button>}</div></div></section>:<>{loading?<p>جارٍ تحميل دروسك…</p>:<div className="course-grid">{courses.map(c=><article className="course-card" key={c.id}><div className="card-top"><span className={`pill ${c.published?'':'draft-pill'}`}>{c.published?'منشور للطلاب':'مسودة خاصة'}</span><BookOpen size={23}/></div><span className="grade-badge">{gradeLabel(c.grade)}</span><h2>{c.title}</h2><p>{c.description}</p><div className="course-counts"><span>{c.definition.lessons.length} محطات</span><span>{c.definition.questions.length} أسئلة</span><span>{c.students||0} طلاب</span></div><div className="course-card-actions"><button className="primary" onClick={()=>edit(c)}>تعديل المحتوى</button>{c.published===1&&<><button className="secondary" onClick={()=>copy(c.id)} aria-label="نسخ رابط الدرس"><Share2 size={17}/></button><a className="secondary" href={`/?course=${encodeURIComponent(c.id)}`}>معاينة</a></>}</div></article>)}</div>}<div className="teacher-backup"><div><h2>احتفظ بنسخة من دروسك</h2><p>نزّل الدروس المنشورة والمسودات مع الشرح والأسئلة والإجابات وأسباب التصحيح. النسخة تشمل آخر ما حفظته، ويمكن استخدامها لاستعادة المحتوى أو نقله لاحقًا.</p><small>لا تتضمن هذه النسخة أسماء الطلاب أو نتائجهم. نسخة كود الموقع مستقلة عن محتوى الدروس.</small></div><a className="secondary" href="/api/teacher/export" download><Download size={18}/>تنزيل نسخة الدروس</a></div><div className="teacher-info"><GraduationCap size={25}/><div><strong>أنت تدير المحتوى، والطلاب يبدأون بأسمائهم</strong><p>لكل درس شرح وتمارين وتصحيح مفسّر ولوحة نتائج وشهادة إتمام. احفظه كمسودة ليبقى خاصًا، وانشره عندما يصبح جاهزًا.</p></div></div></>}
<footer><span>ALWADANI</span><small>مساحة المعلم · خاصة بمالك الموقع</small></footer></main></div>;}
