'use client';
import {useState} from 'react';
import {Award,BookOpen,ChevronDown,ClipboardList,GraduationCap,Menu,Settings,LogOut,ArrowUpRight,Users} from 'lucide-react';
import useWorkspaceNavigation from '../use-workspace-navigation';
export default function TeacherShell({username,current,children}:{username:string;current:'lessons'|'classes'|'records'|'settings'|'students';children:React.ReactNode}){
  const {open,setOpen,mobile}=useWorkspaceNavigation();
  const [busy,setBusy]=useState(false),[error,setError]=useState('');
  async function logout(){setBusy(true);setError('');try{const pending:Promise<boolean>[]=[];window.dispatchEvent(new CustomEvent('alwadani-before-signout',{detail:pending}));if((await Promise.all(pending)).some(saved=>!saved))throw new Error('احفظ تعديلات الكشف أو نسخة جديدة قبل تسجيل الخروج.');const response=await fetch('/api/teacher/auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'logout'})});if(!response.ok)throw new Error('تعذر تسجيل الخروج.');window.location.replace('/teacher');}catch(e){setError((e as Error).message);setBusy(false);}}
  return <div className="teacher-workspace" dir="rtl"><header className="topbar teacher-topbar"><div className="teacher-topbar-start"><button className="workspace-menu" onClick={()=>setOpen(!open)} aria-expanded={open} aria-controls="teacher-navigation" aria-label="إظهار أو إخفاء قائمة المعلم"><Menu size={22}/></button><a className="brand" href="/teacher"><span className="brand-mark">A<span>✦</span></span><span className="wordmark">ALWADANI<small>TEACHER STUDIO</small></span></a></div><span className="workspace-user">{username}<small>مساحة المعلم</small></span></header>{mobile&&open&&<button type="button" className="workspace-nav-backdrop" aria-label="إغلاق القائمة" onClick={()=>setOpen(false)}/>}<div className={'workspace-layout '+(!open?'nav-collapsed':'')}><aside id="teacher-navigation" className="workspace-sidebar" hidden={!open}><div className="sidebar-label">مساحة عملك</div><nav aria-label="قائمة المعلم" onClick={e=>{if(mobile&&(e.target as HTMLElement).closest('a'))setOpen(false);}}><details open><summary><GraduationCap size={19}/><span>الصفوف والدروس</span><ChevronDown size={16}/></summary><a href="/teacher/classes" aria-current={current==='classes'?'page':undefined}><GraduationCap size={18}/>الصفوف</a><a href="/teacher" aria-current={current==='lessons'?'page':undefined}><BookOpen size={18}/>إدارة الدروس</a></details><a href="/teacher/students" aria-current={current==='students'?'page':undefined}><Users size={19}/>المشاركون والنتائج</a><a href="/teacher/records" aria-current={current==='records'?'page':undefined}><ClipboardList size={19}/>الكشوفات</a><a href="/tools/certificates"><Award size={19}/>الشهادات</a><a href="/tools/records"><ClipboardList size={19}/>الكشوف العامة</a><a href="/teacher/settings" aria-current={current==='settings'?'page':undefined}><Settings size={19}/>الإعدادات</a></nav><div className="sidebar-bottom"><a href="/"><ArrowUpRight size={17}/>عرض صفحة الطلاب</a><button disabled={busy} onClick={logout}><LogOut size={17}/>{busy?'جارٍ الخروج…':'تسجيل الخروج'}</button>{error&&<p role="alert">{error}</p>}</div></aside><div className="workspace-content">{children}</div></div></div>;
}
