'use client';
import {useEffect,useRef,useState} from 'react';
import {Heart,Play,RotateCcw,Trophy,Volume2,VolumeX} from 'lucide-react';
import {balloonLevels,wordScenes,type BalloonDifficulty} from '@/lib/chores-learning';
import type {AssessedGame,GameBest} from '@/lib/balloon-assessment';
import ChoresPicture from './chores-picture';
import {useLearningAudio} from './learning-audio';
export default function BalloonGame({game,gameBest,busy,onAction,onFinish,quizTotal,dictationTotal}:{quizTotal:number;dictationTotal:number;game:AssessedGame|null;gameBest:GameBest|null;busy:boolean;onAction:(body:Record<string,unknown>)=>Promise<unknown>;onFinish:()=>void}){
 const [difficulty,setDifficulty]=useState<BalloonDifficulty>(game?.difficulty||'easy'),[lastCorrect,setLastCorrect]=useState('');
 const audio=useLearningAudio(),level=balloonLevels[game?.difficulty||difficulty],playArea=useRef<HTMLDivElement>(null),continueButton=useRef<HTMLButtonElement>(null);
 const run=game?{lives:game.lives,score:game.solved,popped:game.popped,feedback:game.feedback,status:game.status}:null,round=game?{word:game.word,options:game.options}:null,roundIndex=game?.roundIndex||0;
 useEffect(()=>{if(game)setDifficulty(game.difficulty);},[game?.id]);
 useEffect(()=>{if(game)playArea.current?.scrollIntoView({block:'start',behavior:'auto'});},[game?.id]);
 useEffect(()=>{if(game?.feedback==='wrong')continueButton.current?.focus({preventScroll:true});},[game?.feedback]);
 useEffect(()=>{if(game?.feedback!=='correct'||game.status!=='playing')return;const timer=window.setTimeout(()=>{void step('game-next');},650);return()=>window.clearTimeout(timer);},[game?.id,game?.revision]);
 useEffect(()=>{if(game?.word.en&&game.status==='playing'&&!game.feedback)audio.pronounce(game.word.en);},[game?.id,game?.roundIndex,game?.feedback]);
 async function step(action:string,selection?:string){if(!game)return null;return await onAction({action,run:game.id,revision:game.revision,...(selection?{selection}:{})});}
 async function start(nextLevel=difficulty){audio.unlock();setDifficulty(nextLevel);setLastCorrect('');await onAction({action:'game-start',difficulty:nextLevel,restart:!!game});}
 async function pop(en:string){if(!game||busy||game.feedback||game.status!=='playing')return;audio.unlock();const result=await step('game-pop',en);if(!result)return;const correct=en===game.word.en;audio.popSound(correct);if(correct)setLastCorrect(game.word.en+' = '+game.options.find(o=>o.en===en)?.ar);else{setLastCorrect('');audio.pronounce(game.word.en);}}
 function resume(){audio.playEffect('tap');void step('game-resume');}
 const picked=game?.options.find(w=>w.en===game.popped[game.popped.length-1]),correcting=game?.feedback==='wrong';
 return <section className="balloon-game" aria-label="لعبة بالونات المعاني" data-audio-state={audio.audioState}><div className="balloon-game-heading"><div><span className="chores-kicker">POP & LEARN</span><h2>اسمع، شاهد، وفجّر البالونة<span>!</span></h2><p>الإجابة الصحيحة تنقلك تلقائيًا للكلمة التالية. نتوقف فقط لنتعلّم من الخطأ.</p></div><span className="balloon-heading-icon" aria-hidden="true">🎈</span></div>
 <div className="balloon-settings"><div><strong>اختر مستوى التحدّي</strong><div className="balloon-levels" role="group" aria-label="مستوى صعوبة البالونات">{(Object.keys(balloonLevels) as BalloonDifficulty[]).map(id=><button key={id} disabled={busy} aria-pressed={difficulty===id} onClick={()=>{setDifficulty(id);audio.playEffect('tap');if(game)void start(id);}}><b>{balloonLevels[id].label}</b><small>{balloonLevels[id].description}</small></button>)}</div><small>تغيير المستوى يبدأ جولة جديدة بثلاث محاولات.</small></div><div className="balloon-audio-controls"><button className="secondary compact" onClick={audio.toggleSound} aria-pressed={audio.sound}>{audio.sound?<Volume2 size={18}/>:<VolumeX size={18}/>} {audio.sound?'المؤثرات مفعّلة':'المؤثرات مكتومة'}</button><button className="secondary compact" onClick={()=>audio.playEffect('correct')}>جرّب الصوت</button></div></div>
 {!round||!run||!game?<div className="balloon-intro"><div className="balloon-intro-art" aria-hidden="true">🎈 ✦ 🎈</div><h3>المحطة الأخيرة — 12 بالونة و12 نقطة</h3><p>اسمع الإنجليزية واختر الصورة والمعنى. الصحيح من أول محاولة يمنحك نقطة. إكمال الكلمات الـ12 مطلوب للشهادة، ولك 3 محاولات للخطأ.</p><button className="primary" disabled={busy} onClick={()=>void start()}><Play size={18}/>ابدأ لعبة البالونات</button></div>:<>
 <div ref={playArea} className="balloon-play-area"><div className="balloon-game-toolbar"><span className="balloon-lives" aria-label={`المحاولات المتبقية: ${run.lives} من 3`}>{[0,1,2].map(i=><Heart key={i} size={23} className={i<run.lives?'heart-full':'heart-empty'} fill={i<run.lives?'currentColor':'none'}/>)}<b>{run.lives} / 3</b></span><span className="balloon-current-level">{level.label}</span><span>الكلمة <b>{roundIndex+1}</b> / {game.total} · الكلمات <b>{run.score}</b> · النقاط <b>{game.score} / {game.total}</b></span><span className="balloon-live-tag">{correcting?'لحظة للتعلّم':run.status==='won'?'أحسنت!':'◉ الحركة مستمرة'}</span></div>
 <div className={'balloon-stage'+(correcting?' is-correcting':'')+(run.status==='won'?' is-stopped':'')} aria-label="بالونات الترجمة"><span className="balloon-cloud cloud-a" aria-hidden="true"/><span className="balloon-cloud cloud-b" aria-hidden="true"/><div className="balloon-stage-hint" aria-hidden="true">اختَر الصورة والمعنى، لا اللون</div>{round.options.map((option,i)=>{const popped=run.popped.includes(option.en);return <button key={roundIndex+'-'+option.en} type="button" aria-label={'بالونة: '+option.ar} aria-pressed={popped} disabled={busy||popped||correcting||run.status!=='playing'||run.feedback==='correct'} className={'meaning-balloon visual-balloon balloon-color-'+i+(popped?' is-popped':'')} style={{'--lane':(round.options.length>4?(i%3+.5)*100/3:12.5+i*25)+'%','--flight':(level.seconds+(difficulty==='easy'?i*.8:i%3*.4))+'s','--delay':(-level.seconds*(round.options.length>4?.2+Math.floor(i/3)*.36+i%3*.025:.2+i%2*.18))+'s','--still-top':(round.options.length>4?12+Math.floor(i/3)*45:i%2?37:14)+'%'} as React.CSSProperties} onClick={()=>pop(option.en)}>{!popped&&<ChoresPicture scene={wordScenes[option.en]} className="balloon-mini-picture"/>}<span>{popped?'✦':option.ar}</span>{popped&&<span className="balloon-burst" aria-hidden="true">{Array.from({length:8},(_,j)=><b key={j} style={{'--ray':j*45+'deg'} as React.CSSProperties}/>)}</span>}<i aria-hidden="true"/></button>})}
 {correcting&&<div className="balloon-correction-card" role="alert"><ChoresPicture scene={wordScenes[round.word.en]}/><strong dir="ltr">{round.word.en}</strong><b>{round.word.ar}</b><p>اخترت معنى {picked?.en}. {round.word.tip}</p>{run.status==='lost'?<><p>انتهت المحاولات الثلاث. نتعلّم ثم نحاول من جديد.</p><button ref={continueButton} disabled={busy} className="primary" onClick={()=>start()}><RotateCcw size={17}/>أعد اللعبة — 3 محاولات جديدة</button></>:<button ref={continueButton} disabled={busy} className="primary" onClick={resume}>فهمت، أكمل اللعب</button>}</div>}</div>
 <div className="balloon-question"><small>اسمع العبارة واختر بالونتها</small><div className="balloon-word-to-hear"><strong dir="ltr">{round.word.en}</strong><button onClick={()=>audio.pronounce(round.word.en)} className="word-speaker" aria-label="اسمع نطق كلمة اللعبة"><Volume2 size={21}/></button></div><span>{run.feedback==='correct'&&run.status!=='won'?'أحسنت! ننتقل تلقائيًا…':'الصور تساعدك على الفهم'}</span></div></div>
 <div className="balloon-flow-feedback" role="status" aria-live="polite">{lastCorrect?<span>✓ آخر إجابة صحيحة: <bdi>{lastCorrect}</bdi></span>:<span>الصحيح يكمل الرحلة تلقائيًا. الخطأ يشرح لك المعنى.</span>}</div>
 {run.status==='won'&&<div className="balloon-result"><Trophy size={36}/><h3>أتممت الرحلة! شهادتك جاهزة.</h3><p>نقاط هذه اللعبة {game.score} / {game.total} · أفضل لعبة مكتملة {gameBest?.score??game.score} / {game.total}</p><button className="primary" onClick={onFinish}>استلم شهادتك باسمك</button><button className="secondary" disabled={busy} onClick={()=>void start()}><RotateCcw size={17}/>أحسّن نقاط البالونات</button></div>}
 </>}
 {audio.audioNotice&&<p className="audio-notice" role="status">{audio.audioNotice}</p>}<p className="balloon-score-note">اللعبة جزء مطلوب من الرحلة. تُعتمد نقاطها بعد إكمالها: {quizTotal} للتدريبات + {dictationTotal} للإملاء + 12 للبالونات = {quizTotal+dictationTotal+12} نقطة. التصحيح لا يمنح نقطة للكلمة بعد الخطأ. الأفضل يبقى محفوظًا عند إعادة اللعبة أو الاختبار.</p>
 </section>;
}
