'use client';
import {useEffect,useRef,useState} from 'react';
import {Heart,Play,RotateCcw,Trophy,Volume2,VolumeX} from 'lucide-react';
import {initialBalloonRun,makeBalloonRounds,popBalloon,balloonLevels,wordScenes,type BalloonDifficulty,type BalloonRound,type BalloonRun} from '@/lib/chores-learning';
import ChoresPicture from './chores-picture';
import {useLearningAudio} from './learning-audio';
export default function BalloonGame(){
 const [rounds,setRounds]=useState<BalloonRound[]>([]),[run,setRun]=useState<BalloonRun>(initialBalloonRun),[roundIndex,setRoundIndex]=useState(0),[selected,setSelected]=useState(''),[difficulty,setDifficulty]=useState<BalloonDifficulty>('easy'),[lastCorrect,setLastCorrect]=useState('');
 const audio=useLearningAudio(),level=balloonLevels[difficulty],playArea=useRef<HTMLDivElement>(null),continueButton=useRef<HTMLButtonElement>(null),round=rounds[roundIndex];
 useEffect(()=>{if(rounds.length)playArea.current?.scrollIntoView({block:'start',behavior:'auto'});},[rounds]);
 useEffect(()=>{if(run.feedback==='wrong')continueButton.current?.focus({preventScroll:true});},[run.feedback]);
 useEffect(()=>{if(run.feedback!=='correct'||run.status!=='playing')return;const timer=window.setTimeout(()=>{setRun(r=>({...r,popped:[],feedback:null}));setRoundIndex(i=>i+1);setSelected('');audio.pronounce(rounds[roundIndex+1].word.en);},650);return()=>window.clearTimeout(timer);},[run.feedback,run.status,roundIndex]);
 function start(nextLevel=difficulty){audio.unlock();const nextRounds=makeBalloonRounds(Math.random,nextLevel);setRounds(nextRounds);setRun({...initialBalloonRun,popped:[]});setRoundIndex(0);setSelected('');setLastCorrect('');audio.pronounce(nextRounds[0].word.en);}
 function pop(en:string){if(run.feedback==='wrong')return;const next=popBalloon(run,round,en,rounds.length);if(next===run)return;audio.popSound(en===round.word.en);setRun(next);setSelected(en);if(en===round.word.en)setLastCorrect(round.word.en+' = '+round.word.ar);else{setLastCorrect('');audio.narrate(round.word.en,round.word.ar+'. '+round.word.tip);}}
 function resume(){audio.playEffect('tap');audio.stopSpeaking();setRun(r=>({...r,feedback:null}));setSelected('');audio.pronounce(round.word.en);}
 const picked=round?.options.find(w=>w.en===selected),correcting=run.feedback==='wrong';
 return <section className="balloon-game" aria-label="لعبة بالونات المعاني" data-audio-state={audio.audioState}><div className="balloon-game-heading"><div><span className="chores-kicker">POP & LEARN</span><h2>اسمع، شاهد، وفجّر البالونة<span>!</span></h2><p>الإجابة الصحيحة تنقلك تلقائيًا للكلمة التالية. نتوقف فقط لنتعلّم من الخطأ.</p></div><span className="balloon-heading-icon" aria-hidden="true">🎈</span></div>
 <div className="balloon-settings"><div><strong>اختر مستوى التحدّي</strong><div className="balloon-levels" role="group" aria-label="مستوى صعوبة البالونات">{(Object.keys(balloonLevels) as BalloonDifficulty[]).map(id=><button key={id} aria-pressed={difficulty===id} onClick={()=>{setDifficulty(id);audio.playEffect('tap');if(rounds.length)start(id);}}><b>{balloonLevels[id].label}</b><small>{balloonLevels[id].description}</small></button>)}</div><small>تغيير المستوى يبدأ جولة جديدة بثلاث محاولات.</small></div><div className="balloon-audio-controls"><button className="secondary compact" onClick={audio.toggleSound} aria-pressed={audio.sound}>{audio.sound?<Volume2 size={18}/>:<VolumeX size={18}/>} {audio.sound?'المؤثرات مفعّلة':'المؤثرات مكتومة'}</button><button className="secondary compact" onClick={()=>audio.playEffect('correct')}>جرّب الصوت</button></div></div>
 {!round?<div className="balloon-intro"><div className="balloon-intro-art" aria-hidden="true">🎈 ✦ 🎈</div><h3>12 كلمة، 3 محاولات، وحركة مستمرة</h3><p>اسمع الكلمة واختر بالونة صورتها ومعناها. كل إجابة صحيحة تنتقل تلقائيًا، والخطأ يعرض التصحيح قبل متابعة اللعب.</p><button className="primary" onClick={()=>start()}><Play size={18}/>ابدأ لعبة البالونات</button></div>:<>
 <div ref={playArea} className="balloon-play-area"><div className="balloon-game-toolbar"><span className="balloon-lives" aria-label={`المحاولات المتبقية: ${run.lives} من 3`}>{[0,1,2].map(i=><Heart key={i} size={23} className={i<run.lives?'heart-full':'heart-empty'} fill={i<run.lives?'currentColor':'none'}/>)}<b>{run.lives} / 3</b></span><span className="balloon-current-level">{level.label}</span><span>الكلمة <b>{roundIndex+1}</b> / {rounds.length} · الصحيح <b>{run.score}</b></span><span className="balloon-live-tag">{correcting?'لحظة للتعلّم':run.status==='won'?'أحسنت!':'◉ الحركة مستمرة'}</span></div>
 <div className={'balloon-stage'+(correcting?' is-correcting':'')+(run.status==='won'?' is-stopped':'')} aria-label="بالونات الترجمة"><span className="balloon-cloud cloud-a" aria-hidden="true"/><span className="balloon-cloud cloud-b" aria-hidden="true"/><div className="balloon-stage-hint" aria-hidden="true">اختَر الصورة والمعنى، لا اللون</div>{round.options.map((option,i)=>{const popped=run.popped.includes(option.en);return <button key={roundIndex+'-'+option.en} type="button" aria-label={'بالونة: '+option.ar} aria-pressed={popped} disabled={popped||correcting||run.status!=='playing'||run.feedback==='correct'} className={'meaning-balloon visual-balloon balloon-color-'+i+(popped?' is-popped':'')} style={{'--lane':(round.options.length>4?(i%3+.5)*100/3:12.5+i*25)+'%','--flight':(level.seconds+(difficulty==='easy'?i*.8:i%3*.4))+'s','--delay':(-level.seconds*(round.options.length>4?.2+Math.floor(i/3)*.36+i%3*.025:.2+i%2*.18))+'s','--still-top':(round.options.length>4?12+Math.floor(i/3)*45:i%2?37:14)+'%'} as React.CSSProperties} onClick={()=>pop(option.en)}>{!popped&&<ChoresPicture scene={wordScenes[option.en]} className="balloon-mini-picture"/>}<span>{popped?'✦':option.ar}</span>{popped&&<span className="balloon-burst" aria-hidden="true">{Array.from({length:8},(_,j)=><b key={j} style={{'--ray':j*45+'deg'} as React.CSSProperties}/>)}</span>}<i aria-hidden="true"/></button>})}
 {correcting&&<div className="balloon-correction-card" role="alert"><ChoresPicture scene={wordScenes[round.word.en]}/><strong dir="ltr">{round.word.en}</strong><b>{round.word.ar}</b><p>اخترت معنى {picked?.en}. {round.word.tip}</p>{run.status==='lost'?<><p>انتهت المحاولات الثلاث. نتعلّم ثم نحاول من جديد.</p><button ref={continueButton} className="primary" onClick={()=>start()}><RotateCcw size={17}/>أعد اللعبة — 3 محاولات جديدة</button></>:<button ref={continueButton} className="primary" onClick={resume}>فهمت، أكمل اللعب</button>}</div>}</div>
 <div className="balloon-question"><small>اسمع العبارة واختر بالونتها</small><div className="balloon-word-to-hear"><strong dir="ltr">{round.word.en}</strong><button onClick={()=>audio.pronounce(round.word.en)} className="word-speaker" aria-label="اسمع نطق كلمة اللعبة"><Volume2 size={21}/></button></div><span>{run.feedback==='correct'&&run.status!=='won'?'أحسنت! ننتقل تلقائيًا…':'الصور تساعدك على الفهم'}</span></div></div>
 <div className="balloon-flow-feedback" role="status" aria-live="polite">{lastCorrect?<span>✓ آخر إجابة صحيحة: <bdi>{lastCorrect}</bdi></span>:<span>الصحيح يكمل الرحلة تلقائيًا. الخطأ يشرح لك المعنى.</span>}</div>
 {run.status==='won'&&<div className="balloon-result"><Trophy size={36}/><h3>بطل المعاني! أتقنت الكلمات الـ12.</h3><p>بقيت لديك {run.lives} محاولات.</p><button className="primary" onClick={()=>start()}><RotateCcw size={17}/>ألعب مرة أخرى</button></div>}
 </>}
 {audio.audioNotice&&<p className="audio-notice" role="status">{audio.audioNotice}</p>}<p className="balloon-score-note">البالونات تدريب حر. تحديات الصور في «الشرح والتدريب» تحفظ نتيجتك في لوحة المنافسة، ويمكن إعادة الاختبار لتحسينها.</p>
 </section>;
}
