'use client';
import {useState} from 'react';
import {BookOpen,ChevronDown,Bus,Sun,House,Volume2,Play,ChevronLeft,ChevronRight} from 'lucide-react';
import {choresWords,extraChoresWords,choresDialogue,perfectSchoolDay,wordScenes} from '@/lib/chores-learning';

import ChoresPicture from './chores-picture';
import {useLearningAudio} from './learning-audio';
export function ChoresWelcome({onStart}:{onStart:()=>void}){
 return <section className="chores-welcome" aria-label="رحلة الأعمال المنزلية"><div className="chores-welcome-copy"><span className="chores-kicker">UNIT 2 · CHORES</span><h2>يوم صغير، إنجازات كبيرة<span>!</span></h2><p>استيقظ، استعد للرحلة، وساعد جدك وجدتك. أكمل المشاهد الثلاثة وتدريباتها بالترتيب، ثم إملاء الكلمات ولعبة البالونات لتحصل على شهادتك.</p><div className="chores-route" aria-label="رحلة الدرس"><span><Sun size={17}/>صباحي</span><i aria-hidden="true">←</i><span><Bus size={17}/>رحلتي</span><i aria-hidden="true">←</i><span><House size={17}/>أساعد أسرتي</span></div><button className="primary" onClick={onStart}>ابدأ رحلتك بالصور</button></div><div className="chores-welcome-art" aria-hidden="true"><span className="chores-art-sun">☀</span><span className="chores-art-cloud one"/><span className="chores-art-cloud two"/><div className="chores-art-bus"><span>54</span><i/><i/><b>ALWADANI</b><em/><em/></div><div className="chores-art-road"/><span className="chores-art-leaf">✦</span></div></section>;
}
export default function ChoresStudy({station}:{station:number}){
 const [index,setIndex]=useState(0),[animation,setAnimation]=useState(0),[moving,setMoving]=useState(false),[time,setTime]=useState<'habit'|'now'>('habit'),[showExplanation,setShowExplanation]=useState(false);
 const audio=useLearningAudio(),group=station===0?'morning':station===1?'bus':'home',words=choresWords.filter(w=>w.group===group),word=words[index]||words[0];
 function see(i:number){setIndex(i);setShowExplanation(false);setMoving(true);setAnimation(n=>n+1);audio.playEffect('tap');audio.pronounce(words[i].en);}
 function watch(){setMoving(true);setAnimation(n=>n+1);audio.pronounce(word.en);}
 function reader(title:string,lines:string[][]){return <details className="chores-reader"><summary className="chores-reader-title"><BookOpen size={20}/>{title}<ChevronDown size={16}/></summary>{lines.map(([en,ar],i)=><div className="chores-reader-row" key={en}><details className="chores-reader-line"><summary><span className="chores-line-number">{i+1}</span><span dir="ltr">{en}</span><ChevronDown size={16}/></summary><p>{ar}</p></details><button className="word-speaker" onClick={()=>audio.pronounce(en)} aria-label={'اسمع الجملة بالإنجليزية: '+en}><Volume2 size={17}/></button></div>)}</details>;}
 return <div className="chores-study visual-study" data-audio-state={audio.audioState}><div className="chores-study-heading"><div><span className="chores-kicker">WATCH · HEAR · TRY</span><h3>شاهد الكلمة واسمع نطقها</h3></div><span className="visual-word-count">{index+1} / {words.length}</span></div>
 <div className="visual-scene-player"><button className="visual-scene-screen" onClick={watch} aria-label={'شاهد واسمع '+word.en}><ChoresPicture key={word.en+'-'+animation} scene={wordScenes[word.en]} className={moving?'scene-motion':''}/><span className="visual-screen-play"><Play size={20}/>شاهد واسمع</span></button><div className="visual-scene-caption"><strong dir="ltr">{word.en}</strong><span>{word.ar}</span><div><button className="primary" onClick={watch}><Volume2 size={19}/>اسمع النطق بالإنجليزية</button><button className="secondary" aria-expanded={showExplanation} onClick={()=>{setShowExplanation(v=>!v);setMoving(true);setAnimation(n=>n+1);audio.playEffect('tap');}}>اشرح</button></div>{showExplanation&&<p className="visual-written-explanation" role="status">{word.tip}</p>}</div><div className="visual-scene-nav"><button className="secondary compact" disabled={index===0} onClick={()=>see(index-1)}><ChevronRight size={18}/>الصورة السابقة</button><span>المس كل صورة لتكتشفها</span><button className="secondary compact" disabled={index===words.length-1} onClick={()=>see(index+1)}>الصورة التالية<ChevronLeft size={18}/></button></div></div>
 <div className="visual-word-strip" aria-label="صور جميع كلمات المشهد">{words.map((w,i)=><button key={w.en} aria-label={'اكتشف '+w.en} aria-pressed={i===index} onClick={()=>see(i)}><ChoresPicture scene={wordScenes[w.en]}/><span dir="ltr">{w.en}</span></button>)}</div>
 {station===0&&<div className="visual-time-toggle"><span>اسمع الفرق بين كل يوم والآن</span><div><button aria-pressed={time==='habit'} onClick={()=>{setTime('habit');audio.pronounce('I get dressed every morning.');}}>🔁 كل صباح</button><button aria-pressed={time==='now'} onClick={()=>{setTime('now');audio.pronounce('I am getting dressed now.');}}>⏱️ الآن</button></div><strong dir="ltr">{time==='habit'?'I get dressed every morning.':'I am getting dressed now.'}</strong><span>{time==='habit'?'أرتدي ملابسي كل صباح.':'أنا أرتدي ملابسي الآن.'}</span></div>}
 {station===2&&<><details className="chores-extra-words"><summary>الكلمات الإضافية — نطق إنجليزي وترجمة مكتوبة <ChevronDown size={16}/></summary><div>{extraChoresWords.map(([en,ar])=><p key={en}><b dir="ltr">{en}</b><span>{ar}</span><button className="word-speaker" onClick={()=>audio.pronounce(en)} aria-label={'اسمع النطق بالإنجليزية: '+en}><Volume2 size={17}/></button></p>)}</div></details>{reader('القصة كاملة — استمع أو افتح الترجمة',choresDialogue)}{reader('My Perfect School Day — استمع ليومك المثالي',perfectSchoolDay)}</>}
 {audio.audioNotice&&<p className="audio-notice" role="status">{audio.audioNotice}</p>}
 </div>;
}
