'use client';
import {useState,useEffect} from 'react';
import {BookOpen, Trophy, Award, Check, CheckCircle2, Circle, Download, Share2, RefreshCw, Lightbulb, GraduationCap, Lock, Sparkles} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Progress} from '@/components/ui/progress';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
import type {PublicCourse} from '@/lib/course-types';
import LessonSupport from './lesson-support';
import {gradeLabel} from '@/lib/grades';
type Answer={question:number;choice:number;correct:number;answer:number;reason:string;answerText:string};
type Student={id:string;name:string;completed:string|null};
type Rank={id:string;name:string;completed:string|null;answered:number;score:number};
type State={student:Student|null;answers:Answer[];reads:number[];leaderboard:Rank[];course?:PublicCourse};
const empty:State={student:null,answers:[],reads:[],leaderboard:[]};
export default function Classroom({course:initialCourse}:{course:PublicCourse}){
 const [data,setData]=useState<State>(empty),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[name,setName]=useState(''),[lesson,setLesson]=useState(0),[tab,setTab]=useState('learn'),[mode,setMode]=useState('explain'),[qi,setQi]=useState(0),[choice,setChoice]=useState(''),[notice,setNotice]=useState(''),[switchStudent,setSwitchStudent]=useState(false);
 const course=data.course||initialCourse,lessons=course.lessons,questions=course.questions;
 const unit=lessons[lesson],list=questions.filter(q=>q.lesson===lesson),question=list[Math.min(qi,list.length-1)],answer=data.answers.find(a=>a.question===question?.id),score=data.answers.reduce((n,a)=>n+a.correct,0),progress=Math.round((data.answers.length+data.reads.length)/(questions.length+lessons.length)*100);
 async function load(resume=false){setError('');try{const res=await fetch('/api/classroom?course='+encodeURIComponent(initialCourse.id));const d=await res.json() as State & {error?:string};if(!res.ok)throw new Error(d.error||'تعذّر تحميل البيانات.');setData(d);if(resume&&d.student){const current=d.course||initialCourse;const next=current.questions.find(q=>!d.answers.some((a:Answer)=>a.question===q.id));if(next){setLesson(next.lesson);setQi(current.questions.filter(q=>q.lesson===next.lesson).findIndex(q=>q.id===next.id));setMode(d.reads.includes(next.lesson)?'practice':'explain');}else{setLesson(current.lessons.length-1);setQi(current.questions.filter(q=>q.lesson===current.lessons.length-1).length-1);setMode('practice');}}}catch(e){setError(e instanceof Error?e.message:'تعذّر الاتصال.');}finally{setLoading(false);}}
 useEffect(()=>{void load(true);},[]);
 async function action(body:Record<string,unknown>){setBusy(true);setError('');try{const res=await fetch('/api/classroom',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...body,course:initialCourse.id})});const d=await res.json() as State & {error?:string};if(!res.ok)throw new Error(d.error||'تعذّر تحميل البيانات.');setData(d);return true;}catch(e){setError(e instanceof Error?e.message:'تعذّر الاتصال.');return false;}finally{setBusy(false);}}
 function openLesson(index:number){setLesson(index);setMode('explain');setQi(0);setChoice('');setError('');}
 async function start(e:React.FormEvent){e.preventDefault();if(await action({action:'start',name})){openLesson(0);setSwitchStudent(false);}}
 async function practice(){if(!data.student){document.getElementById('student-name')?.focus();setError('أدخل اسمك لبدء التدريب وحفظ نتيجتك.');return;}if(await action({action:'read',lesson})){const first=list.findIndex(q=>!data.answers.some(a=>a.question===q.id));setQi(first<0?0:first);setChoice('');setMode('practice');}}
 function next(){setChoice('');if(qi<list.length-1)setQi(qi+1);else if(lesson<lessons.length-1)openLesson(lesson+1);}
 useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const ac=new AbortController();Promise.resolve(context.registerTool({name:'read_course_progress',title:'قراءة تقدم الطالب',description:'Return the current saved student progress, score and certificate status.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:async(input:unknown)=>{if(!input||typeof input!=='object'||Object.keys(input).length)throw new Error('Expected an empty object');const res=await fetch('/api/classroom?course='+encodeURIComponent(initialCourse.id));const d=await res.json() as State & {error?:string};if(!res.ok)throw new Error(d.error||'تعذّر تحميل البيانات.');return {name:d.student?.name??null,answered:d.answers.length,total:questions.length,score:d.answers.reduce((n:number,a:Answer)=>n+a.correct,0),certificateReady:!!d.student?.completed};}},{signal:ac.signal})).catch(()=>{});return()=>ac.abort();},[initialCourse.id]);
 async function certificateBlob(){const s=data.student;if(!s?.completed)throw new Error('أكمل التدريب أولًا.');await document.fonts.ready;const c=document.createElement('canvas');c.width=1800;c.height=1250;const x=c.getContext('2d')!;x.fillStyle='#fcfdfc';x.fillRect(0,0,c.width,c.height);x.strokeStyle='#bf963e';x.lineWidth=6;x.strokeRect(35,35,1730,1180);x.lineWidth=1;x.strokeRect(55,55,1690,1140);x.fillStyle='#102f2c';x.fillRect(55,55,1690,150);x.textAlign='center';x.fillStyle='#f4cf82';x.font='bold 45px Georgia';x.fillText('ALWADANI · LEARNING STUDIO',900,150);x.fillStyle='#102f2c';x.font='bold 72px Arial';x.fillText('شهادة إتمام',900,330);x.font='32px Arial';x.fillText('تشهد منصة Alwadani بأن الطالب / الطالبة',900,440);let fontSize=76;x.font=`bold ${fontSize}px Arial`;while(x.measureText(s.name).width>1500&&fontSize>30){fontSize-=2;x.font=`bold ${fontSize}px Arial`;}x.fillText(s.name,900,565);x.fillStyle='#607671';x.font='32px Arial';x.fillText('أكمل شرح وتدريبات الدرس',900,670);x.fillText(course.title,900,735,1500);x.fillStyle='#102f2c';x.font='bold 46px Arial';x.fillText(`النتيجة: ${score} / ${questions.length}  (${Math.round(score/questions.length*100)}%)`,900,850);x.font='28px Arial';x.fillText(`تاريخ الإتمام: ${new Date(s.completed).toLocaleDateString('ar-SA',{timeZone:'Asia/Riyadh',calendar:'gregory'})}`,900,960);x.font='22px Arial';x.fillText(`رقم الشهادة: ${s.id.slice(0,16)}`,900,1040);x.fillText('شهادة إتمام تدريب إلكتروني · الدرجة من الإجابة الأولى',900,1120);return new Promise<Blob>((resolve,reject)=>c.toBlob(b=>b?resolve(b):reject(new Error('تعذّر إنشاء الشهادة.')),'image/png'));}
 async function download(){try{const blob=await certificateBlob();const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='Alwadani-Certificate.png';a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);setNotice('تم تنزيل الشهادة. يمكنك إرفاقها وإرسالها للمعلم.');}catch(e){setError((e as Error).message);}}
 async function share(){try{const blob=await certificateBlob();const file=new File([blob],'Alwadani-Certificate.png',{type:'image/png'});if(navigator.canShare?.({files:[file]})){await navigator.share({files:[file],title:'شهادة إتمام '+course.title,text:`شهادة ${data.student?.name} — النتيجة ${score}/${questions.length}`});}else await download();}catch(e){if((e as Error).name!=='AbortError')setError('تعذّرت المشاركة. استخدم تنزيل الشهادة.');}}
 return <div className="site" dir="rtl"><header className="topbar"><a className="brand" href="/" aria-label="Alwadani الصفحة الرئيسية"><span className="brand-mark">A<span>✦</span></span><span className="wordmark">ALWADANI<small>LEARNING STUDIO</small></span></a><div className="course-label"><a href={`/?grade=${encodeURIComponent(initialCourse.grade||'general')}`}>{gradeLabel(initialCourse.grade)}</a></div><div className="top-student"><GraduationCap size={20}/>{data.student?.name||'مساحة الطالب'}</div></header>
 <main><div className="page-heading"><div><div className="eyebrow">ALWADANI LEARNING STUDIO</div><h1>{course.title}<span>.</span></h1><p>افهم الشرح، جرّب ما تعلمت، وتقدّم بثقة.</p></div><div className="unit-stamp"><BookOpen size={25}/><span>{course.title}<small>شرح بالعربية · أمثلة بالإنجليزية</small></span></div></div>
 {(!data.student||switchStudent)&&<form className="enrollment" onSubmit={start}><div><strong>رحلتك تبدأ باسمك</strong><p>سيظهر اسمك في لوحة النتائج وعلى شهادة الإتمام.</p></div><div className="name-fields"><label htmlFor="student-name" className="sr-only">اسم الطالب على الشهادة</label><input id="student-name" maxLength={60} minLength={2} required value={name} onChange={e=>setName(e.target.value)} placeholder="اسم الطالب على الشهادة" disabled={busy||loading}/><button className="primary" disabled={busy||loading}>{loading?'جارٍ التحميل…':busy?'جارٍ الحفظ…':'ابدأ التعلم'}</button></div></form>}
 {data.student&&<div className="journey"><div><strong>مرحبًا، {data.student.name}</strong><span>{data.answers.length} من {questions.length} سؤالًا · {score} إجابة صحيحة</span><button className="switch-student" onClick={()=>setSwitchStudent(v=>!v)}>{switchStudent?'إلغاء':'طالب آخر على هذا الجهاز'}</button></div><div className="journey-bar"><span>تقدم الرحلة <b>{progress}%</b></span><Progress value={progress} aria-label="تقدم الرحلة"/></div></div>}
 {error&&<div role="alert" className="error-banner">{error}<button onClick={()=>load()}>إعادة تحميل النتائج</button></div>}
 <Tabs value={tab} onValueChange={v=>{setTab(v);if(v==='leaderboard')void load();}} dir="rtl"><TabsList className="main-tabs"><TabsTrigger value="learn"><BookOpen/>الشرح والتدريب</TabsTrigger><TabsTrigger value="leaderboard"><Trophy/>لوحة النتائج</TabsTrigger><TabsTrigger value="certificate"><Award/>شهادتي</TabsTrigger></TabsList>
 <TabsContent value="learn"><div className="learning-grid"><aside className="lesson-rail"><div className="rail-label">مسار الدرس <span>{lessons.length} محطات</span></div><ol>{lessons.map((l,i)=>{const done=questions.filter(q=>q.lesson===i).every(q=>data.answers.some(a=>a.question===q.id));return <li key={l.en}><button className={`lesson-link ${i===lesson?'active':''}`} onClick={()=>openLesson(i)}><span className={`lesson-number ${done?'done':''}`}>{done?<Check size={18}/>:l.tag}</span><span><strong>{l.title}</strong><small dir="ltr">{l.en}</small></span>{i===lesson&&<span className="active-dot"/>}</button></li>;})}</ol><div className="rail-tip"><Lightbulb size={22}/><strong>الخطأ جزء من التعلم</strong><p>اقرأ سبب التصحيح قبل الانتقال إلى السؤال التالي.</p></div><div className="rail-bottom"><Award size={19}/><span>شهادتك بانتظارك عند النهاية</span></div></aside>
 <section className="lesson-panel"><div className="lesson-top"><span className="pill">المحطة {lesson+1} / {lessons.length}</span><span className="meta">{list.length} أسئلة تدريبية</span></div><div className="lesson-title"><h2>{unit.title}</h2><span dir="ltr">{unit.en}</span></div>
 <div className="mode-switch"><button className={mode==='explain'?'selected':''} onClick={()=>setMode('explain')}>١. افهم القاعدة</button><button className={mode==='practice'?'selected':''} onClick={practice} disabled={busy}>٢. طبّق ما تعلمت</button></div>
 {mode==='explain'?<><p className="intro">{unit.intro}</p><div className="formula"><small>بناء الجملة</small><strong dir="ltr">{unit.formula}</strong></div><div className="rules">{unit.rules.map(([title,description,ex],i)=><article key={title}><span className="rule-index">{i+1}</span><div><h3>{title}</h3><p>{description}</p><div className="english" dir="ltr">{ex}</div></div></article>)}</div><div className="note"><Lightbulb size={19}/><p>{unit.note}</p></div><div className="example-strip"><span>مثال في السياق</span><p dir="ltr">{unit.example}</p><small>{unit.translation}</small></div><LessonSupport key={course.id+unit.en} courseId={course.id} unit={unit.en}/><div className="panel-footer"><span>جاهز للتطبيق؟</span><button className="primary" onClick={practice} disabled={busy}>انتقل إلى التدريب</button></div></>:<div className="practice"><div className="question-top"><span>السؤال {qi+1} من {list.length}</span><span>الدرجة من أول إجابة</span></div><Progress value={(qi+1)/list.length*100} aria-label="تقدم أسئلة الدرس"/><h3>اختر الإجابة الصحيحة</h3><p className="question-sentence" dir="ltr">{question.prompt}</p><RadioGroup value={answer?String(answer.choice):choice} onValueChange={setChoice} disabled={!!answer||busy} dir="ltr" className="choices">{question.options.map((o,i)=><label className={`answer-option ${answer?(i===answer.answer?'correct':i===answer.choice?'incorrect':''):choice===String(i)?'picked':''}`} key={o} htmlFor={`q${question.id}-${i}`}><RadioGroupItem id={`q${question.id}-${i}`} value={String(i)}/><span>{o}</span>{answer&&i===answer.answer&&<CheckCircle2 size={20}/>}</label>)}</RadioGroup>{!answer?<button className="primary check-answer" disabled={choice===''||busy} onClick={()=>action({action:'answer',question:question.id,choice:Number(choice)})}>{busy?'جارٍ التصحيح…':'تحقق من الإجابة'}</button>:<><div className={`feedback ${answer.correct?'success':'correction'}`} role="status"><strong>{answer.correct?'أحسنت، إجابة صحيحة!':'لنراجع الإجابة معًا'}</strong>{!answer.correct&&<p>اخترت <b dir="ltr">{question.options[answer.choice]}</b>، والصحيح <b dir="ltr">{answer.answerText}</b>.</p>}<p>{answer.reason}</p><div className="correct-sentence" dir="ltr">{question.prompt.replace('___',answer.answerText)}</div></div>{qi===list.length-1&&lesson===lessons.length-1?<button className="primary" disabled={busy||data.answers.length!==questions.length||data.reads.length!==lessons.length} onClick={async()=>{if(await action({action:'complete'}))setTab('certificate');}}>أكمل الرحلة واستلم شهادتك</button>:<button className="primary" onClick={next}>{qi===list.length-1?'الدرس التالي':'السؤال التالي'}</button>}</>}</div>}
 </section></div></TabsContent>
 <TabsContent value="leaderboard"><section className="standalone"><div className="section-heading"><div><div className="eyebrow">LEADERBOARD</div><h2>لوحة الإنجاز</h2><p>نتائج فعلية تتحدث مع كل إجابة. الترتيب حسب الإجابات الصحيحة، ثم عدد الأسئلة المكتملة. تُجمع نتائج كل نسخة من محتوى الدرس على حدة.</p></div><button className="secondary" onClick={()=>load()} disabled={busy}><RefreshCw size={17}/>تحديث</button></div>{data.leaderboard.length?<Table className="ranking"><TableHeader><TableRow><TableHead>الترتيب</TableHead><TableHead>الطالب</TableHead><TableHead>الإجابات الصحيحة</TableHead><TableHead>التقدم</TableHead><TableHead>الحالة</TableHead></TableRow></TableHeader><TableBody>{data.leaderboard.map((r,i)=><TableRow key={r.id} className={r.id===data.student?.id?'my-row':''}><TableCell><span className={`rank rank-${i}`}>{i===0?<Trophy size={18}/>:i+1}</span></TableCell><TableCell><strong>{r.name}</strong>{r.id===data.student?.id&&<small className="you">أنت</small>}</TableCell><TableCell><b>{r.score}</b> / {questions.length}</TableCell><TableCell>{r.answered} / {questions.length}</TableCell><TableCell>{r.completed?'أكمل الرحلة':'يتدرّب'}</TableCell></TableRow>)}</TableBody></Table>:<div className="empty-state"><Trophy size={45}/><h3>المركز الأول ينتظرك</h3><p>تظهر أسماء الطلاب هنا بعد أول إجابة. لا توجد نتائج بعد.</p><button className="primary" onClick={()=>setTab('learn')}>اذهب إلى التدريب</button></div>}<div className="note"><Lightbulb size={19}/><p>لكل سؤال نقطة واحدة إذا كانت الإجابة الأولى صحيحة. التصحيح يساعدك على التعلم، ولا يغيّر درجتك السابقة. تكرار الإجابة لا يضيف نقاطًا.</p></div></section></TabsContent>
 <TabsContent value="certificate"><section className="standalone certificate-section">{data.student?.completed?<><div className="section-heading"><div><div className="eyebrow">JOURNEY COMPLETE</div><h2>أنجزت رحلتك، {data.student.name}!</h2><p>احتفظ بشهادتك وشاركها مع معلمك.</p></div><Sparkles className="gold" size={32}/></div><div className="certificate" id="certificate"><div className="certificate-brand">ALWADANI <span>LEARNING STUDIO</span></div><Award size={58} className="certificate-award"/><div className="certificate-kicker">CERTIFICATE OF COMPLETION</div><h2>شهادة إتمام</h2><p>تُمنح هذه الشهادة إلى</p><h3>{data.student.name}</h3><p>لإكمال شرح وتدريبات الدرس</p><strong className="certificate-course">{course.title}</strong><div className="certificate-topics" dir="ltr">{lessons.map(l=>l.en||l.title).join(' · ')}</div><div className="certificate-details"><div><span>النتيجة</span><strong>{score} / {questions.length}</strong></div><div><span>تاريخ الإتمام</span><strong>{new Date(data.student.completed).toLocaleDateString('ar-SA',{timeZone:'Asia/Riyadh',calendar:'gregory'})}</strong></div></div><div className="certificate-id">رقم الشهادة: <bdi>{data.student.id.slice(0,16)}</bdi><br/>شهادة إتمام تدريب إلكتروني · الدرجة من الإجابة الأولى</div></div><div className="certificate-actions"><button className="primary" onClick={download}><Download size={18}/>تنزيل الشهادة</button><button className="secondary" onClick={share}><Share2 size={18}/>مشاركة مع المعلم</button><button className="secondary" onClick={()=>window.print()}>طباعة / حفظ PDF</button></div>{notice&&<p className="download-notice" role="status">{notice}</p>}</>:<div className="empty-state"><div className="locked-award"><Award size={57}/><Lock size={21}/></div><h2>خطوة بعد خطوة، نحو شهادتك</h2><p>أكمل قراءة المحطات الـ{lessons.length} والإجابة عن الأسئلة الـ{questions.length}، ثم استلم شهادة باسمك ونتيجتك.</p><Progress value={progress} aria-label="التقدم نحو الشهادة"/><span>{progress}% مكتمل</span><button className="primary" onClick={()=>setTab('learn')}>متابعة التعلم</button>{data.answers.length===questions.length&&data.reads.length===lessons.length&&<button className="secondary" disabled={busy} onClick={()=>action({action:'complete'})}>إصدار شهادة الإتمام</button>}</div>}</section></TabsContent>
 </Tabs><footer><span>ALWADANI</span><p>{course.title}</p><small>تعلّم بفهم، وتقدّم بثقة.</small></footer></main></div>;
}
