'use client';
import {useState} from 'react';
import {Search,ChevronLeft,ChevronRight,Clock3} from 'lucide-react';
import type {Rank} from '@/lib/classroom-results';
import {formatSolveTime} from '@/lib/solve-time';
import {audienceWords,participantNoun,type Gender} from '@/lib/audience';
const medalNames=['الميدالية الذهبية، المركز الأول','الميدالية الفضية، المركز الثاني','الميدالية البرونزية، المركز الثالث','الميدالية الزرقاء، المركز الرابع','الميدالية الخضراء، المركز الخامس'];
const medalPlaces=['المركز الأول','المركز الثاني','المركز الثالث','المركز الرابع','المركز الخامس'];
const hasMedal=(row:Rank)=>!!row.completed&&row.position>=1&&row.position<=medalNames.length;
function MedalSymbol({position,size=25}:{position:number;size?:number}){return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d="M7.21 15 2.66 7.14a2 2 0 0 1 .13-2.2L4.4 2.8A2 2 0 0 1 6 2h12a2 2 0 0 1 1.6.8l1.6 2.14a2 2 0 0 1 .14 2.2L16.79 15M11 12 5.12 2.2M13 12l5.88-9.8M8 7h8"/><circle cx="12" cy="17" r="5"/><text x="12" y="19.6" textAnchor="middle" fill="currentColor" stroke="none" fontSize="7.5" fontWeight="700" fontFamily="Arial">{position}</text></svg>;}
function SolveTime({row}:{row:Rank}){const measured=typeof row.solveMs==='number',time=measured?row.solveMs:row.estimatedSolveMs;return row.completed?<span className="competition-time"><Clock3 size={13}/>{typeof time==='number'?<>{measured?'وقت الحل':'وقت تقديري'} <bdi dir="ltr">{formatSolveTime(time)}</bdi></>:'الوقت غير مسجّل'}</span>:null;}
export default function ClassroomLeaderboard({rows,studentId,studentGender='male'}:{rows:Rank[];studentId?:string;studentGender?:Gender}){
 const words=audienceWords({studentGender});
 const [search,setSearch]=useState(''),[page,setPage]=useState(0),perPage=20;
 const filtered=rows.filter(r=>r.name.includes(search.trim())),pages=Math.max(1,Math.ceil(filtered.length/perPage)),current=Math.min(page,pages-1),visible=filtered.slice(current*perPage,(current+1)*perPage),mine=rows.find(r=>r.id===studentId);
 return <div className="competition-board"><div className="competition-top"><span><b>{rows.length}</b> {participantNoun(rows.length,studentGender)} في المنافسة</span>{mine&&<strong>مركزك #{mine.position} · أفضل نتيجة {Math.round(mine.percentage)}%</strong>}</div>
 {rows.some(hasMedal)&&<div className="competition-podium">{rows.filter(hasMedal).slice(0,medalNames.length).map(r=><article key={r.id} className={'podium-'+r.position}><span className="podium-medal" role="img" aria-label={medalNames[r.position-1]}>{r.position<=3?['🥇','🥈','🥉'][r.position-1]:<MedalSymbol position={r.position} size={43}/>}</span><span className="podium-place">{medalPlaces[r.position-1]}</span><strong>{r.name}</strong><b>{Math.round(r.percentage)}%</b><small dir="ltr">{r.score} / {r.total}</small><SolveTime row={r}/></article>)}</div>}
 <label className="competition-search"><Search size={19}/><input aria-label={`ابحث باسم ${words.student} في لوحة النتائج`} placeholder={`ابحث باسم ${words.student}`} value={search} onChange={e=>{setSearch(e.target.value);setPage(0);}}/></label>
 <div className="competition-list" aria-label={`جميع نتائج ${words.students}`}>{visible.map(r=><article key={r.id} className={'competition-row'+(r.id===studentId?' my-result':'')}><span className={'competition-position'+(hasMedal(r)?' competition-medal medal-'+r.position:'')} aria-label={hasMedal(r)?medalNames[r.position-1]:`المركز ${r.position}`}>{hasMedal(r)?<MedalSymbol position={r.position}/>:r.position}</span><div className="competition-name"><strong>{r.name}{r.id===studentId&&<small>أنت</small>}</strong><span>{r.completed?(r.gameTotal?words.finishedJourney:words.finishedQuiz):r.answered?words.practising:words.preparing} · المحاولات {r.attempts}</span></div><div className="competition-score"><b>{Math.round(r.percentage)}%</b><span>{r.score} / {r.total} · حل {r.answered} / {r.total}</span>{r.gameTotal&&<span className="competition-parts">التدريبات {r.quizScore} / {r.quizTotal} · الإملاء {r.dictationScore} / {r.dictationTotal} · البالونات {r.gameScore} / {r.gameTotal}{!r.gameCompleted?' · اللعبة مطلوبة':''}</span>}<SolveTime row={r}/></div></article>)}</div>
 {!visible.length&&<p className="competition-empty">{search?'لم نجد اسمًا مطابقًا.':`المركز الأول بانتظار أول ${words.noun} ${studentGender==='female'?'تبدأ رحلتها':'يبدأ رحلته'}.`}</p>}
 <div className="competition-pages"><button className="secondary compact" disabled={current===0} onClick={()=>setPage(current-1)}><ChevronRight size={17}/>السابق</button><span>الصفحة {current+1} / {pages} · {filtered.length} نتيجة</span><button className="secondary compact" disabled={current>=pages-1} onClick={()=>setPage(current+1)}>التالي<ChevronLeft size={17}/></button></div>
 </div>;
}
