import type {Lesson,QuizQuestion,TeacherCourse} from './course-types';
import {CHORES_COURSE_ID} from './chores-learning';

const lessons:Lesson[]=[
 {title:'من الاستيقاظ إلى ارتداء الملابس',en:'My Morning',tag:'01',intro:'شاهد ما يفعله الطفل، واضغط «شاهد واسمع» لتسمع العبارة ومعناها.',formula:'wake up → get up → get dressed',rules:[['wake up — أستيقظ','أفتح عيني وأصبح مستيقظًا. قد أبقى في السرير قليلًا لأقرأ.','I wake up at five o’clock.'],['get up — أنهض من السرير','أترك السرير وأبدأ يومي. لهذا أستطيع أن أستيقظ الساعة الخامسة، ثم أنهض الساعة الخامسة والنصف.','I wake up at five, but I get up at 5:30.'],['get dressed / get undressed','get dressed = أرتدي ملابسي. get undressed = أخلع ملابسي. نستخدم الثانية قبل تبديل الملابس أو النوم.','I get dressed in the morning. I get undressed before bed.']],note:'تخيّل خطوتين: عيناك تفتحان = wake up، ثم قدماك تلمسان الأرض وتترك السرير = get up.',example:'I wake up, get up, and get dressed.',translation:'أستيقظ، ثم أنهض من السرير، وأرتدي ملابسي.'},
 {title:'رحلتي بالحافلة',en:'On the Bus',tag:'02',intro:'شاهد خطوات رحلة الحافلة: نلحق بها، نصعد، نركب، ثم ننزل.',formula:'catch the bus → get on → ride → get off',rules:[['catch the bus — ألحق بالحافلة','أصل في الوقت المناسب حتى لا تفوتني الحافلة. لا نترجم catch هنا إلى أمسك بيدي.','Hurry up! You need to catch the bus at nine.'],['get on / get off','get on the bus = أصعد إلى الحافلة. get off the bus = أنزل منها. on وoff تغيّران المعنى تمامًا.','I get on at home. I get off at school.'],['ride / comic book','ride = أركب أو رحلة ركوب. comic book = كتاب قصص مصوّرة يمكن قراءته خلال الرحلة.','I ride on the bus and read my comic book.']],note:'احفظ العبارة مع الحافلة: get on the bus وget off the bus. لا تستخدم on عندما تقصد النزول.',example:'We get on the 54 bus and get off at the park.',translation:'نصعد إلى الحافلة رقم 54 وننزل عند الحديقة.'},
 {title:'أساعد جدي وجدتي',en:'Helping at Home',tag:'03',intro:'شاهد كيف نساعد الجد والجدة. اضغط كل صورة لتسمع اسمها ومعناها.',formula:'collect leaves · water flowers · clean the yard',rules:[['grandparents — الجد والجدة','grandpa هو الجد، وgrandma هي الجدة. كلمة grandparents تجمعهما معًا.','I visit my grandparents in the afternoon.'],['leaves — أوراق الشجر','leaf مفرد، وleaves جمع. نستخدم collect مع الأوراق لأننا نجمعها من الأرض.','We collect leaves.'],['trash can / flowers / yard','trash can = سلة المهملات، flowers = الأزهار، yard = الفناء. water كفعل تعني يسقي.','We put leaves in the trash can and water the flowers.']],note:'في trash can، كلمة can جزء من اسم سلة المهملات. أما We can help فتعني نستطيع المساعدة.',example:'I help my grandparents. I collect leaves and water the flowers.',translation:'أساعد جدي وجدتي. أجمع أوراق الشجر وأسقي الأزهار.'},

];
const questions:QuizQuestion[]=[];
function q(lesson:number,audio:string,options:string[],reason:string){const answer=options.indexOf(audio);if(answer<0)throw new Error('Missing answer');questions.push({id:questions.length+1,lesson,prompt:audio,options,answer,reason,audio,kind:'picture-choice'});}
q(0,'wake up',['wake up','get up','get dressed','get undressed'],'wake up = أستيقظ. في الصورة أفتح عيني وما زلت في السرير. النهوض وترك السرير هو get up.');
q(0,'get up',['get up','wake up','get dressed','get undressed'],'get up = أنهض من السرير. الطفل ترك السرير ووقف. فتح العينين فقط هو wake up.');
q(0,'get dressed',['get dressed','get undressed','wake up','get up'],'get dressed = أرتدي ملابسي. القميص الجاهز للارتداء يدل على الاستعداد للصباح.');
q(0,'get undressed',['get undressed','get dressed','get up','wake up'],'get undressed = أخلع ملابسي. الملابس تتجه إلى السلة بعد خلعها؛ وهي عكس get dressed.');
q(1,'catch the bus',['catch the bus','get on the bus','ride on the bus','get off the bus'],'catch the bus = ألحق بالحافلة. الطفل يسرع حتى يصل إليها قبل أن تغادر، ولم يصعد إليها بعد.');
q(1,'get on the bus',['get on the bus','get off the bus','ride on the bus','comic book'],'get on the bus = أصعد إلى الحافلة. السهم يتجه إلى الحافلة. النزول منها هو get off the bus.');
q(1,'get off the bus',['get off the bus','get on the bus','ride on the bus','catch the bus'],'get off the bus = أنزل من الحافلة. السهم يبتعد عن الحافلة بعد الوصول.');
q(1,'comic book',['comic book','ride on the bus','get on the bus','get off the bus'],'comic book = كتاب قصص مصوّرة. الرسم يظهر صفحات قصة فيها صور وحوار، نقرأها أثناء الرحلة.');
q(2,'grandparents',['grandparents','flowers','leaves','trash can'],'grandparents = الجد والجدة معًا. تظهر في الصورة شخصيتان من كبار السن.');
q(2,'leaves',['leaves','flowers','trash can','chores'],'leaves = أوراق الشجر. نرى أوراقًا متناثرة على الأرض، أما flowers فهي الأزهار.');
q(2,'trash can',['trash can','comic book','leaves','flowers'],'trash can = سلة المهملات. نضع فيها أوراق الشجر بعد جمعها من الأرض.');
q(2,'flowers',['flowers','leaves','grandparents','trash can'],'flowers = الأزهار. لها بتلات ملونة، ونساعد الأسرة بسقيها بالماء.');
export const choresCourse:TeacherCourse={id:CHORES_COURSE_ID,grade:'grade-4',title:'الأعمال المنزلية · Chores',description:'3 مشاهد تفاعلية بالصورة والنطق، جميع الكلمات وترجماتها، 12 تحديًا بالصور، بالونات مستمرة وأفضل نتائج الطلاب.',published:1,definition:{lessons,questions},updated:'2026-10-10'};
