import type {Lesson,QuizQuestion,TeacherCourse} from './course-types';
import {CHORES_COURSE_ID} from './chores-learning';

const lessons:Lesson[]=[
 {title:'من الاستيقاظ إلى ارتداء الملابس',en:'My Morning',tag:'01',intro:'قبل أن نذهب إلى المدرسة نمر بخطوات صغيرة. نتعلم العبارة الإنجليزية كاملة، ثم نربطها بالحركة التي نقوم بها. انتبه: الاستيقاظ ليس هو النهوض من السرير.',formula:'wake up → get up → get dressed',rules:[['wake up — أستيقظ','أفتح عيني وأصبح مستيقظًا. قد أبقى في السرير قليلًا لأقرأ.','I wake up at five o’clock.'],['get up — أنهض من السرير','أترك السرير وأبدأ يومي. لهذا أستطيع أن أستيقظ الساعة الخامسة، ثم أنهض الساعة الخامسة والنصف.','I wake up at five, but I get up at 5:30.'],['get dressed / get undressed','get dressed = أرتدي ملابسي. get undressed = أخلع ملابسي. نستخدم الثانية قبل تبديل الملابس أو النوم.','I get dressed in the morning. I get undressed before bed.']],note:'تخيّل خطوتين: عيناك تفتحان = wake up، ثم قدماك تلمسان الأرض وتترك السرير = get up.',example:'I wake up, get up, and get dressed.',translation:'أستيقظ، ثم أنهض من السرير، وأرتدي ملابسي.'},
 {title:'رحلتي بالحافلة',en:'On the Bus',tag:'02',intro:'في القصة يزور الأطفال الجد والجدة بالحافلة رقم 54. لكل مرحلة من الرحلة عبارة مختلفة: ألحق بالحافلة، أصعد، أركب، ثم أنزل.',formula:'catch the bus → get on → ride → get off',rules:[['catch the bus — ألحق بالحافلة','أصل في الوقت المناسب حتى لا تفوتني الحافلة. لا نترجم catch هنا إلى أمسك بيدي.','Hurry up! You need to catch the bus at nine.'],['get on / get off','get on the bus = أصعد إلى الحافلة. get off the bus = أنزل منها. on وoff تغيّران المعنى تمامًا.','I get on at home. I get off at school.'],['ride / comic book','ride = أركب أو رحلة ركوب. comic book = كتاب قصص مصوّرة يمكن قراءته خلال الرحلة.','I ride on the bus and read my comic book.']],note:'احفظ العبارة مع الحافلة: get on the bus وget off the bus. لا تستخدم on عندما تقصد النزول.',example:'We get on the 54 bus and get off at the park.',translation:'نصعد إلى الحافلة رقم 54 وننزل عند الحديقة.'},
 {title:'أساعد جدي وجدتي',en:'Helping at Home',tag:'03',intro:'Chores تعني الأعمال المنزلية التي نشارك بها لمساعدة الأسرة. في هذه الصفحات يجمع الأطفال أوراق الشجر ويسقون الأزهار وينظّفون الفناء.',formula:'collect leaves · water flowers · clean the yard',rules:[['grandparents — الجد والجدة','grandpa هو الجد، وgrandma هي الجدة. كلمة grandparents تجمعهما معًا.','I visit my grandparents in the afternoon.'],['leaves — أوراق الشجر','leaf مفرد، وleaves جمع. نستخدم collect مع الأوراق لأننا نجمعها من الأرض.','We collect leaves.'],['trash can / flowers / yard','trash can = سلة المهملات، flowers = الأزهار، yard = الفناء. water كفعل تعني يسقي.','We put leaves in the trash can and water the flowers.']],note:'في trash can، كلمة can جزء من اسم سلة المهملات. أما We can help فتعني نستطيع المساعدة.',example:'I help my grandparents. I collect leaves and water the flowers.',translation:'أساعد جدي وجدتي. أجمع أوراق الشجر وأسقي الأزهار.'},
 {title:'افهم القصة والفرق بين العادة والآن',en:'The Story & Useful Patterns',tag:'04',intro:'اقرأ حوار القصة وترجمته، ثم لاحظ كيف نتكلم عن عادة يومية، أو فعل يحدث الآن، أو طلب من شخص آخر. الهدف أن تفهم المعنى قبل اختيار الإجابة.',formula:'I get up every day. / I am getting up now.',rules:[['العادة اليومية: I + الفعل','عندما أحكي عن يومي المعتاد أستخدم I get up أو I get dressed. usually تعني عادةً، وsometimes تعني أحيانًا.','I usually wake up at five o’clock.'],['الآن: am / is / are + فعل ينتهي بـ ing','I’m هي اختصار I am. جملة I’m getting dressed now تعني أن ارتداء الملابس يحدث الآن. لاحظ get → getting بحرفي t.','I’m waking up. I’m getting dressed now.'],['الطلب أو الأمر: ابدأ بالفعل','Get up now! = انهض الآن! Hurry up! = أسرع! Put your clothes on. = ارتدِ ملابسك.','Get up now! Put your gardening clothes on.'],['السؤال عن القدرة: Can we + الفعل؟','Can we collect leaves? تعني هل يمكننا جمع أوراق الشجر؟ تأتي collect بعد can دون s أو ing.','Can we collect leaves? We can help.']],note:'لا نخلط بين I get dressed every morning (عادة) وI’m getting dressed now (الآن). اقرأ كلمات الزمن لتعرف المقصود.',example:'I get dressed every morning. I’m getting dressed now.',translation:'أرتدي ملابسي كل صباح. أنا أرتدي ملابسي الآن.'},
 {title:'طبّق: يومي خطوة بخطوة',en:'My Daily Routine',tag:'05',intro:'هذه محطة إكمال جمل اليوم المعتاد من الصفحات المرفقة. اقرأ الجملة وما بعدها: هل ما زلت في السرير؟ هل تصعد إلى الحافلة أم تلحق بها؟ اختَر العبارة التي تناسب السياق.',formula:'at + time · in the morning · before bed',rules:[['استدل بكلمات الجملة','read in bed يخبرك أنك ما زلت في السرير. take a shower يحدث بعد النهوض. أمام الملابس نفكر في get dressed.','I get up and take a shower.'],['أفعال الحافلة ليست متطابقة','catch the bus = ألحق بها في الوقت المحدد. get on the bus = أصعد. get off the bus = أنزل عند الوصول.','I catch the bus, then I get on it.'],['المساعدة قبل النوم وبعد الظهر','visit my grandparents = أزور جدي وجدتي. brush my teeth = أنظّف أسناني. get undressed = أخلع ملابسي.','Before I go to bed, I get undressed and brush my teeth.']],note:'الوقت يساعدك على ترتيب اليوم، لكن المعنى هو الذي يحدد الإجابة؛ لا تعتمد على حفظ مكان الخيار.',example:'In the afternoon, I visit my grandparents and help at home.',translation:'بعد الظهر، أزور جدي وجدتي وأساعد في المنزل.'},
 {title:'طبّق: يوم مدرسي مثالي',en:'My Perfect School Day',tag:'06',intro:'اقرأ الفقرة المترجمة ثم أكمل فراغاتها كما في صفحة الكتاب. الربط بين الجمل مهم: أقرأ في السرير، ثم أنهض، ثم أرتدي ملابسي. بعد ذلك أصعد إلى الحافلة وأنزل عند المدرسة.',formula:'wake up → get up → get dressed → go to school',rules:[['استخدم ترتيب الأحداث','الفقرة تبدأ بالاستيقاظ والقراءة في السرير. الخطوة التالية هي النهوض، ثم ارتداء الملابس.','I wake up and read in bed. I get up at 5:30.'],['ابحث عن الاسم بعد الفعل','read تحتاج شيئًا نقرأه مثل comic book. visit تحتاج شخصًا مثل grandparents. water تحتاج شيئًا نسقيه مثل flowers.','I read a comic book, visit my grandparents, and water flowers.'],['اتجاه الحركة يحدد on أو off','أمام المنزل نصعد get on. أمام المدرسة ننزل get off. عندما نريد اللحاق برحلة أخرى نستخدم catch.','I get on the bus at home and get off at school.']],note:'كلمة wake up محلولة أصلًا في الفقرة. بقيت تسعة فراغات؛ ستجيب عنها واحدًا تلو الآخر مع سبب التصحيح.',example:'In the evening, I get undressed and go to bed at eight o’clock.',translation:'في المساء، أخلع ملابسي وأذهب إلى النوم الساعة الثامنة.'},
 {title:'مراجعة أخيرة ثم تحدّي البالونات',en:'Review & Balloon Challenge',tag:'07',intro:'نراجع فراغات نشاط القراءة من الصفحة الثانية، ثم نميز العادة من الفعل الذي يحدث الآن. بعد التمارين يمكنك اللعب: اختر بالونة الترجمة الصحيحة للكلمة التي تظهر أسفل الشاشة.',formula:'Understand → practise → play',rules:[['أكمل بالمعنى','eat breakfast يأتي بعد النهوض وارتداء الملابس. reading my new ... يحتاج اسمًا لشيء نقرأه.','Get up, get dressed, and eat breakfast.'],['لا تترجم كلمة واحدة بمعزل عن العبارة','get on وget off وget up عبارات مختلفة؛ لا يكفي أن ترى get لتعرف الإجابة.','get up = leave bed; get on = board; get off = leave the bus'],['قواعد اللعبة','لديك ثلاث محاولات في الجولة الكاملة. كل بالونة خاطئة تفقدك محاولة مع شرح. بعد الإجابة الصحيحة انتقل للكلمة التالية. إذا نفدت المحاولات ابدأ اللعبة من جديد.','Pop the balloon with the correct Arabic meaning.']],note:'نشاط Listen, read, and complete قُدّم هنا كتدريب قراءة؛ لم يُرفق تسجيل صوتي في الصور. درجة الشهادة ولوحة النتائج تعتمد على التمارين، ويمكن إعادة اللعبة للتدريب بحرية.',example:'I’m reading my new comic book on the bus now.',translation:'أنا أقرأ كتاب القصص المصوّرة الجديد في الحافلة الآن.'}
];
const questions:QuizQuestion[]=[];
function q(lesson:number,prompt:string,options:string[],answer:string,reason:string){const index=options.indexOf(answer);if(index<0)throw new Error('Missing chores answer');questions.push({id:questions.length+1,lesson,prompt,options,answer:index,reason});}
q(0,'أفتح عيني بعد النوم: ___ up.', ['wake','get','ride','catch'],'wake','wake up تعني أستيقظ؛ أفتح عيني بعد النوم. get up تعني أنهض وأترك السرير، وقد تأتي بعد الاستيقاظ.');
q(0,'أترك السرير وأقف: ___ up.', ['get','wake','read','put'],'get','get up تعني أنهض من السرير. إذا كنت أفتح عيني فقط فهذه wake up.');
q(0,'ألبس ملابسي: get ___.', ['dressed','undressed','off','on'],'dressed','get dressed تعني أرتدي ملابسي. get undressed عكسها: أخلع ملابسي.');
q(0,'أخلع ملابسي لتبديلها: get ___.', ['undressed','dressed','up','on'],'undressed','get undressed تعني أخلع ملابسي؛ نستخدمها لتبديل الملابس أو قبل النوم.');
q(0,'ما معنى get up؟', ['أنهض من السرير','أستيقظ','أركب الحافلة','أخلع ملابسي'],'أنهض من السرير','get up هو النهوض وترك السرير. wake up هو الاستيقاظ فقط؛ لذلك لا نختاره عندما يُسأل عن get up.');
q(0,'I open my eyes, but I stay in bed. I ___.', ['wake up','get up','get off','get undressed'],'wake up','أفتح عيني لكنني أبقى في السرير: هذا wake up. عبارة get up تتطلب أن أنهض وأترك السرير.');
q(1,'ألحق بالحافلة قبل أن تغادر: ___ the bus.', ['catch','collect','water','read'],'catch','catch the bus تعني ألحق بالحافلة في وقتها. collect = يجمع، water = يسقي، read = يقرأ.');
q(1,'أصعد إلى الحافلة: get ___ the bus.', ['on','off','up','undressed'],'on','نستخدم get on the bus للصعود إلى الحافلة. get off the bus للنزول منها.');
q(1,'أنا داخل الحافلة أثناء الرحلة: ___ on the bus.', ['ride','wake','collect','dress'],'ride','ride on the bus تعني أستقل الحافلة أثناء الرحلة. get on هو الصعود نفسه، وليس الرحلة بعد الصعود.');
q(1,'أنزل عند الوصول: get ___ the bus.', ['off','on','up','dressed'],'off','get off the bus تعني أنزل من الحافلة عند الوصول؛ on تعني الصعود، وهي عكس المقصود.');
q(1,'كتاب فيه قصة مرسومة وحوار: ___.', ['comic book','trash can','bus stop','gardening clothes'],'comic book','comic book هو كتاب قصص مصوّرة. يتكون من كلمتين: comic وbook.');
q(1,'We arrive at school. We need to ___ the bus.', ['get off','get on','wake up','get dressed'],'get off','وصلنا إلى المدرسة، إذن نحتاج إلى النزول من الحافلة: get off. get on نستخدمها في بداية الرحلة عند الصعود.');
q(2,'الجد والجدة معًا: ___.', ['grandparents','flowers','leaves','classes'],'grandparents','grandparents تعني الجد والجدة معًا. grandpa للجد، وgrandma للجدة.');
q(2,'أوراق الشجر التي نجمعها من الأرض: ___.', ['leaves','flowers','clothes','books'],'leaves','leaves هي أوراق الشجر، ومفردها leaf. flowers هي الأزهار وليست الأوراق.');
q(2,'نضع النفايات في: ___.', ['trash can','comic book','bus stop','classroom'],'trash can','trash can تعني سلة المهملات. comic book كتاب قصص مصوّرة، وbus stop موقف الحافلات.');
q(2,'We water the ___ in the garden.', ['flowers','comic book','bus','trash can'],'flowers','water كفعل تعني يسقي. نسقي الأزهار flowers؛ بقية الخيارات لا تناسب هذا الفعل في الحديقة.');
q(2,'ما معنى chores؟', ['الأعمال المنزلية','رحلات الحافلة','القصص المصوّرة','الحصص الدراسية'],'الأعمال المنزلية','chores هي الأعمال المنزلية التي نساعد بها الأسرة، مثل جمع الأوراق وسقي الأزهار وتنظيف الفناء.');
q(3,'The bus leaves soon. Mom says: “___!”', ['Hurry up','Get off','Read in bed','Go to bed'],'Hurry up','الحافلة ستغادر قريبًا، لذا تقول الأم أسرع! = Hurry up. get off تعني انزل، ولا تعبّر عن الإسراع.');
q(3,'“I’m getting dressed now” تعني:', ['أنا أرتدي ملابسي الآن','أنا أخلع ملابسي الآن','أنا أستيقظ عادةً','أنا أجمع الأوراق'],'أنا أرتدي ملابسي الآن','I’m = I am، وgetting dressed تعني ارتداء الملابس الآن. get undressed تعني خلع الملابس، وهي مختلفة.');
q(3,'Can we ___ leaves?', ['collect','collecting','collects','collected'],'collect','بعد can نستخدم الفعل بصورته الأساسية: collect. لا نضيف s أو ing، فتكون الجملة هل يمكننا جمع أوراق الشجر؟');
q(4,'1 · I usually ___ at five o’clock.', ['wake up','get undressed','get off','water flowers'],'wake up','الجملة الأولى من النشاط تصف بداية اليوم بالاستيقاظ: wake up. ثم يأتي النهوض في الجملة التالية.');
q(4,'2 · I ___ at 5:15 in the morning and take a shower.', ['get up','wake up','get off','read'],'get up','أنهض الساعة الخامسة والربع ثم أستحم؛ get up تعني أترك السرير. في الجملة السابقة استيقظت الساعة الخامسة بالفعل.');
q(4,'3 · I ___ the bus at 6:30.', ['catch','collect','read','put'],'catch','catch the bus تعني ألحق بالحافلة في موعدها. الوقت 6:30 يحدد موعد اللحاق بها.');
q(4,'4 · At 6:45, I ___ the bus and go to school.', ['get on','get off','get up','get undressed'],'get on','لأذهب إلى المدرسة أصعد إلى الحافلة: get on. get off تعني أنزل عند الوصول.');
q(4,'5 · On the bus, I sometimes read my ___.', ['comic book','trash can','grandparents','leaves'],'comic book','بعد read نحتاج شيئًا نقرأه: comic book = كتاب قصص مصوّرة. grandparents أشخاص نزورهم، لا شيء نقرأه.');
q(4,'6 · In the afternoon, I visit my grandparents and take out their ___.', ['trash can','comic book','bus','clothes'],'trash can','في سياق الأعمال المنزلية take out their trash can تعني أخرج سلة المهملات الخاصة بهما. بقية الكلمات لا تصف هذا العمل في النشاط.');
q(4,'7 · Before I go to bed, I ___ and brush my teeth.', ['get undressed','get on','catch the bus','wake up'],'get undressed','قبل النوم أخلع ملابسي وأنظّف أسناني: get undressed. get dressed تعني أرتدي، وwake up تبدأ بها يومك.');
q(5,'2 · I ___ at 5:30 after reading in bed.', ['get up','wake up','get off','get undressed'],'get up','أنا مستيقظ وأقرأ في السرير بالفعل؛ الخطوة التالية في الفقرة هي النهوض get up عند 5:30.');
q(5,'3 · I ___ in my favorite clothes.', ['get dressed','get undressed','get off','catch'],'get dressed','in my favorite clothes تعني بملابسي المفضلة، فنحتاج get dressed = أرتدي ملابسي، وليس get undressed = أخلعها.');
q(5,'4 · I ___ the bus in front of my house.', ['get on','get off','get up','get dressed'],'get on','أبدأ الرحلة أمام منزلي، لذا أصعد إلى الحافلة get on. جملة الوصول إلى المدرسة تأتي بعدها.');
q(5,'5 · I ___ the bus in front of my school.', ['get off','get on','wake up','get undressed'],'get off','وصلت إلى المدرسة، فأحتاج أن أنزل get off. get on للصعود عند المنزل في الجملة السابقة.');
q(5,'6 · I ___ the number 54 bus to the park.', ['catch','collect','water','read'],'catch','بعد الحصص ألحق بالحافلة رقم 54 إلى الحديقة. catch the bus عبارة مناسبة للحاق بوسيلة النقل.');
q(5,'7 · On the bus, I read my favorite ___.', ['comic book','trash can','grandparents','flowers'],'comic book','ما أقرأه هو كتاب القصص المصوّرة comic book. نفهم الإجابة من الفعل read.');
q(5,'8 · In the afternoon, I visit my ___.', ['grandparents','flowers','leaves','trash can'],'grandparents','visit = يزور، والمقصود زيارة الجد والجدة: grandparents. الأزهار نسقيها، وأوراق الشجر نجمعها.');
q(5,'9 · I water the ___ and clean their yard.', ['flowers','comic book','clothes','bus'],'flowers','water the flowers = أسقي الأزهار. water هنا فعل، وليس اسم الماء.');
q(5,'10 · In the evening, I ___ and go to bed.', ['get undressed','get on','wake up','catch the bus'],'get undressed','في المساء وقبل النوم أخلع ملابسي: get undressed. الاستيقاظ wake up يحدث بعد النوم لا قبله.');
q(6,'1 · Get up, ___, eat a big breakfast.', ['get dressed','get off','get undressed','collect leaves'],'get dressed','المعنى في نشاط القراءة: انهض، ارتدِ ملابسك، وتناول إفطارًا كبيرًا. get dressed هو المناسب للاستعداد صباحًا.');
q(6,'2 · ___ your bus, that’s what I said!', ['Catch','Read','Collect','Water'],'Catch','catch your bus تعني الحق بحافلتك، وهي العبارة المرتبطة بالحافلة هنا.');
q(6,'3 · I need to ___ this bus, but I am really late!', ['get on','get off','get up','get undressed'],'get on','أحتاج إلى الصعود إلى هذه الحافلة وأنا متأخر: get on. الجملة تتحدث عن بداية الركوب لا النزول.');
q(6,'4 · I’m reading my new ___.', ['comic book','trash can','grandparents','leaves'],'comic book','read يحتاج شيئًا نقرأه. comic book كتاب قصص مصوّرة، وهو ما يُقرأ في نشاط الصفحة.');
q(6,'I ___ dressed now.', ['am getting','get','gets','getting'],'am getting','now تعني الآن. مع I نستخدم am ثم getting: I am getting dressed now. getting وحدها تفتقد am.');
q(6,'I ___ up every morning.', ['get','am getting','gets','getting'],'get','every morning تعني كل صباح؛ نتحدث عن عادة، فنقول I get up. مع I لا نضيف s إلى الفعل.');

export const choresCourse:TeacherCourse={id:CHORES_COURSE_ID,grade:'grade-4',title:'الأعمال المنزلية · Chores',description:'زيارة الجد والجدة: ترجمة المفردات، شرح العبارات، 42 تمرينًا بتصحيح مفسّر، ولعبة بالونات بثلاث محاولات.',published:1,definition:{lessons,questions},updated:'2026-10-09'};
