import type {Lesson,QuizQuestion,TeacherCourse} from './course-types';
import {CHORES_COURSE_ID} from './chores-learning';

const lessons:Lesson[]=[
 {title:'من الاستيقاظ إلى ارتداء الملابس',en:'My Morning',tag:'01',intro:'قبل أن نذهب إلى المدرسة نمر بخطوات صغيرة. نتعلم العبارة الإنجليزية كاملة، ثم نربطها بالحركة التي نقوم بها. انتبه: الاستيقاظ ليس هو النهوض من السرير.',formula:'wake up → get up → get dressed',rules:[['wake up — أستيقظ','أفتح عيني وأصبح مستيقظًا. قد أبقى في السرير قليلًا لأقرأ.','I wake up at five o’clock.'],['get up — أنهض من السرير','أترك السرير وأبدأ يومي. لهذا أستطيع أن أستيقظ الساعة الخامسة، ثم أنهض الساعة الخامسة والنصف.','I wake up at five, but I get up at 5:30.'],['get dressed / get undressed','get dressed = أرتدي ملابسي. get undressed = أخلع ملابسي. نستخدم الثانية قبل تبديل الملابس أو النوم.','I get dressed in the morning. I get undressed before bed.']],note:'تخيّل خطوتين: عيناك تفتحان = wake up، ثم قدماك تلمسان الأرض وتترك السرير = get up.',example:'I wake up, get up, and get dressed.',translation:'أستيقظ، ثم أنهض من السرير، وأرتدي ملابسي.'},
 {title:'رحلتي بالحافلة',en:'On the Bus',tag:'02',intro:'في القصة يزور الأطفال الجد والجدة بالحافلة رقم 54. لكل مرحلة من الرحلة عبارة مختلفة: ألحق بالحافلة، أصعد، أركب، ثم أنزل.',formula:'catch the bus → get on → ride → get off',rules:[['catch the bus — ألحق بالحافلة','أصل في الوقت المناسب حتى لا تفوتني الحافلة. لا نترجم catch هنا إلى أمسك بيدي.','Hurry up! You need to catch the bus at nine.'],['get on / get off','get on the bus = أصعد إلى الحافلة. get off the bus = أنزل منها. on وoff تغيّران المعنى تمامًا.','I get on at home. I get off at school.'],['ride / comic book','ride = أركب أو رحلة ركوب. comic book = كتاب قصص مصوّرة يمكن قراءته خلال الرحلة.','I ride on the bus and read my comic book.']],note:'احفظ العبارة مع الحافلة: get on the bus وget off the bus. لا تستخدم on عندما تقصد النزول.',example:'We get on the 54 bus and get off at the park.',translation:'نصعد إلى الحافلة رقم 54 وننزل عند الحديقة.'},
 {title:'أساعد جدي وجدتي',en:'Helping at Home',tag:'03',intro:'Chores تعني الأعمال المنزلية التي نشارك بها لمساعدة الأسرة. في هذه الصفحات يجمع الأطفال أوراق الشجر ويسقون الأزهار وينظّفون الفناء.',formula:'collect leaves · water flowers · clean the yard',rules:[['grandparents — الجد والجدة','grandpa هو الجد، وgrandma هي الجدة. كلمة grandparents تجمعهما معًا.','I visit my grandparents in the afternoon.'],['leaves — أوراق الشجر','leaf مفرد، وleaves جمع. نستخدم collect مع الأوراق لأننا نجمعها من الأرض.','We collect leaves.'],['trash can / flowers / yard','trash can = سلة المهملات، flowers = الأزهار، yard = الفناء. water كفعل تعني يسقي.','We put leaves in the trash can and water the flowers.']],note:'في trash can، كلمة can جزء من اسم سلة المهملات. أما We can help فتعني نستطيع المساعدة.',example:'I help my grandparents. I collect leaves and water the flowers.',translation:'أساعد جدي وجدتي. أجمع أوراق الشجر وأسقي الأزهار.'},
 {title:'يومي في قصة قصيرة',en:'My Day in Pictures',tag:'04',intro:'شاهد خطوات اليوم، ثم راجع الفرق بين ما تفعله كل يوم وما تفعله الآن. القصة الكاملة وجميع كلمات الصفحات موجودة هنا لمن يريد المزيد.',formula:'every morning: I get dressed. / now: I am getting dressed.',rules:[['كل يوم أم الآن؟','every morning تعني كل صباح: عادة يومية. now تعني الآن: am + فعل ينتهي بـ ing.','I get dressed every morning. I am getting dressed now.'],['Can we + الفعل؟','نستخدم بعد can الفعل الأساسي دون s أو ing. Can we collect leaves? = هل يمكننا جمع أوراق الشجر؟','We can collect leaves.'],['عبارات تساعدك','Hurry up! = أسرع! Put your gardening clothes on. = ارتدِ ملابس العمل في الحديقة.','Hurry up! Catch the bus at nine.']],note:'كل الكلمات والترجمات متاحة للمراجعة، لكن التدريب الأساسي قصير: 4 أسئلة فقط في كل محطة. يمكنك إعادة لعبة البالونات متى أردت.',example:'I’m reading my new comic book on the bus now.',translation:'أنا أقرأ كتاب القصص المصوّرة الجديد في الحافلة الآن.'}
];
const questions:QuizQuestion[]=[];
function q(lesson:number,prompt:string,options:string[],answer:string,reason:string,picture:string){const index=options.indexOf(answer);if(index<0)throw new Error('Missing chores answer');questions.push({id:questions.length+1,lesson,prompt,options,answer:index,reason,picture});}
q(0,'Look at the picture. What does the child do?', ['wake up','get up','get dressed','get undressed'],'wake up','wake up تعني أستيقظ؛ الطفل فتح عينيه وما زال في السرير. get up تعني أنهض وأترك السرير.','sun-bed');
q(0,'Look! The child leaves the bed. Choose the phrase.', ['get up','wake up','get off the bus','get undressed'],'get up','get up تعني أنهض من السرير. في الرسم ترك الطفل السرير ووقف، وليس فقط فتح عينيه.','leave-bed');
q(0,'What do you do with these clothes in the morning?', ['get dressed','get undressed','wake up','ride on the bus'],'get dressed','get dressed تعني أرتدي ملابسي للاستعداد صباحًا. get undressed عكسها: أخلع ملابسي.','shirt');
q(0,'Before bed, I ___.', ['get undressed','get dressed','get on the bus','catch the bus'],'get undressed','قبل النوم نخلع الملابس لتبديلها: get undressed. الرسم يوضح الملابس المتجهة إلى السلة بعد خلعها.','laundry');
q(1,'Hurry up! I need to ___ before it leaves.', ['catch the bus','get off the bus','read a comic book','collect leaves'],'catch the bus','catch the bus تعني ألحق بالحافلة قبل أن تغادر. الطفل يسرع للوصول في الوقت المناسب.','run-bus');
q(1,'Follow the arrow. I ___.', ['get on the bus','get off the bus','get up','get undressed'],'get on the bus','السهم يتجه نحو الحافلة للصعود إليها: get on the bus. get off هو النزول والابتعاد عنها.','board-bus');
q(1,'The child is inside the bus. I ___.', ['ride on the bus','get off the bus','wake up','get dressed'],'ride on the bus','ride on the bus تعني أستقل الحافلة أثناء الرحلة. get on هو لحظة الصعود، أما هنا فالطفل جالس بداخلها.','seated-bus');
q(1,'We arrive! Follow the arrow. I ___.', ['get off the bus','get on the bus','catch the bus','get dressed'],'get off the bus','وصلنا، والسهم يبتعد عن الحافلة: get off the bus = أنزل منها. on تعني الصعود، وهي عكس المطلوب.','leave-bus');
q(2,'Who do I visit? Look at the picture.', ['grandparents','flowers','leaves','classes'],'grandparents','grandparents تعني الجد والجدة معًا كما في الرسم. grandpa هو الجد، وgrandma هي الجدة.','family');
q(2,'What do we collect from the ground?', ['leaves','flowers','comic books','clothes'],'leaves','leaves هي أوراق الشجر المتناثرة على الأرض. مفردها leaf، أما flowers فهي الأزهار.','garden');
q(2,'Where do we put the leaves?', ['trash can','comic book','bus stop','classroom'],'trash can','نضع الأوراق المجمعة في سلة المهملات: trash can. كلمة can هنا جزء من اسم السلة وليست فعل القدرة.','bin');
q(2,'We water the ___ in the garden.', ['flowers','leaves','comic book','bus'],'flowers','water كفعل تعني يسقي؛ نسقي الأزهار flowers الظاهرة في الرسم. comic book شيء نقرأه.','flower');
q(3,'What do I read on the bus?', ['comic book','trash can','flowers','gardening clothes'],'comic book','comic book هو كتاب قصص مصوّرة فيه رسوم وحوار كما في الصورة. read تعني يقرأ.','book');
q(3,'Helping at home: collecting leaves and cleaning. These are ___.', ['chores','classes','bus rides','comic books'],'chores','chores هي الأعمال المنزلية التي نساعد بها الأسرة، مثل جمع أوراق الشجر وتنظيف الفناء.','house');
q(3,'I ___ dressed now.', ['am getting','get','gets','getting'],'am getting','now تعني الآن. نستخدم مع I كلمة am ثم getting: I am getting dressed now. getting وحدها ينقصها am.','clock');
q(3,'I ___ up every morning.', ['get','am getting','gets','getting'],'get','every morning تعني كل صباح؛ هذه عادة فنقول I get up. مع I لا نضيف s، وam getting يصف ما يحدث الآن.','leave-bed');
export const choresCourse:TeacherCourse={id:CHORES_COURSE_ID,grade:'grade-4',title:'الأعمال المنزلية · Chores',description:'جميع الكلمات وترجماتها ونطقها، 4 محطات مرئية و16 تمرينًا بتصحيح مفسّر، ولعبة بالونات بثلاثة مستويات وثلاث محاولات.',published:1,definition:{lessons,questions},updated:'2026-10-09'};
