import {recordHeader,recordHeaderCss} from './education-brand';
import {gradeLabel} from './grades';
import {isNumberTask,markClass,markLabel,type RecordContent} from './records';
import {isSchoolBlank,manualRecordBody,manualRecordCss,manualPageCss,manualTotal} from './manual-record';

const escape=(text:unknown)=>String(text??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]!));
export const recordPrintCss='body{margin:0;padding:24px;background:#fff;color:#173b35;font:14px/1.7 Tahoma,Arial,sans-serif;direction:rtl}*{box-sizing:border-box}h1{font-size:25px;margin:0 0 10px}p{margin:5px 0}header{border-bottom:3px solid #146650;padding-bottom:15px;margin-bottom:20px}header small{color:#61776b}table{border-collapse:collapse;width:100%;table-layout:fixed;margin:18px 0}th,td{border:1px solid #b8c9bf;padding:8px 6px;overflow-wrap:anywhere;text-align:center}thead{display:table-header-group}tr{break-inside:avoid}th{background:#e7efeb;font-size:12px}th:first-child{width:36px}.student-name{width:170px;text-align:right}td{height:36px;font-size:12px}.mark-done{background:#ddf1e5;color:#145c38}.mark-missing{background:#fbe1df;color:#952d28}.mark-score{background:#edf3fb;color:#285077}.mark-note{background:#fff4d7;color:#765615}.mark-empty{color:#748277}.record-blank-cell{background:#fff;height:40px}.record-signatures{display:flex;justify-content:space-between;gap:30px;margin-top:25px;border-top:1px solid #c6d2cb;padding-top:14px}.record-signatures p{min-width:180px}.record-print-page+.record-print-page{break-before:page;margin-top:35px}.record-legend{font-size:12px;color:#5b7065}footer{margin-top:25px;font-size:11px;color:#6e8076}a{color:#146650}@media print{@page{size:A4 landscape;margin:12mm}body{padding:0}*{-webkit-print-color-adjust:exact;print-color-adjust:exact}.record-print-page+.record-print-page{margin-top:0}button{display:none}}.education-brand{display:flex;justify-content:space-between;align-items:center;gap:20px;margin-bottom:12px}.education-brand>div{display:grid}.education-brand strong{font-size:20px;color:#237763}.education-brand img{width:90px;height:46px;object-fit:contain}.record-print-page{padding:15px;background:#fff}.record-design-green{background:linear-gradient(150deg,#eaf5ed,#fff 40%);border:1px solid #87b89a}.record-design-blue{background:linear-gradient(150deg,#eaf0fb,#fff 40%);border-top:6px solid #1e3d64}.record-design-gold{border:2px solid #b9954b;background:linear-gradient(150deg,#fcf5e7,#fff 40%)}';
export function recordPrintBody(record:RecordContent){
  if(isSchoolBlank(record))return manualRecordBody(record);
  const sections=[],blank=record.format==='blank';
  for(let start=0;start<record.tasks.length;start+=6){
    const tasks=record.tasks.slice(start,start+6);
    for(let rowStart=0;rowStart<record.students.length;rowStart+=18){
    sections.push('<section class="record-print-page record-design-'+(record.design||'white')+'">'+recordHeader(record)+'<p class="record-range">الأعمال '+(start+1)+'–'+(start+tasks.length)+' من '+record.tasks.length+'</p><table><thead><tr><th>م</th><th class="student-name">اسم الطالب</th>'+tasks.map(t=>'<th>'+escape(t.title)+(!blank&&(isNumberTask(t)||t.type==='performance-score')?'<br>من '+t.maxScore:'')+'</th>').join('')+'</tr></thead><tbody>'+record.students.slice(rowStart,rowStart+18).map((student,i)=>'<tr><td>'+(rowStart+i+1)+'</td><td class="student-name">'+escape(student.name)+'</td>'+tasks.map(task=>{const mark=record.marks[student.id]?.[task.id];return blank?'<td class="record-blank-cell"></td>':'<td class="'+markClass(mark,task)+'">'+escape(markLabel(task,mark))+'</td>';}).join('')+'</tr>').join('')+'</tbody></table>'+(blank?'':'<p class="record-legend">الأخضر: إنجاز / حل الواجب · الأحمر: عدم الإنجاز / عدم الحل / غياب · ألوان التعليقات المخصصة يختارها المعلم · لم يُرصد: لم تُدخل نتيجة بعد</p>')+'<div class="record-signatures"><p>المعلم: '+escape(record.teacherName||'________________')+'</p><p>مدير المدرسة: '+escape(record.principalName||'________________')+'</p></div><footer>نسخة للعرض والطباعة · ALWADANI</footer></section>');
    }
  }
  return sections.join('');
}
export function recordHtml(record:RecordContent){return '<!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>'+escape(record.title)+'</title><style>'+(isSchoolBlank(record)?'body{margin:0;padding:20px;background:#edf2f3}'+manualRecordCss+manualPageCss:recordPrintCss+recordHeaderCss)+'</style></head><body>'+recordPrintBody(record)+'</body></html>';}
export function recordCsv(record:RecordContent){
  const cell=(value:unknown)=>{let text=String(value??'');if(/^[\s]*[=+@-]/.test(text))text="'"+text;return '"'+text.replace(/"/g,'""')+'"';};
  const school=isSchoolBlank(record),rows=[['الكشف',record.title],['الصف',record.classLabel||gradeLabel(record.grade)+(record.className?' '+record.className:'')],['المعلم',record.teacherName,'المدير',record.principalName],[],['م','اسم الطالب',...record.tasks.map(t=>t.title+(school?' (من '+t.maxScore+')':'')),...(school?['المجموع (من '+manualTotal(record.tasks)+')']:[])],...record.students.map((s,i)=>[i+1,s.name,...record.tasks.map(t=>record.format==='blank'?'':markLabel(t,record.marks[s.id]?.[t.id])),...(school?['']:[])])];
  return '\ufeff'+rows.map(row=>row.map(cell).join(',')).join('\r\n');
}
export function downloadRecordFile(content:string,type:string,name:string){const url=URL.createObjectURL(new Blob([content],{type}));const link=document.createElement('a');link.href=url;link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(url),10000);}
