import { sqliteTable, text, integer, primaryKey, index } from 'drizzle-orm/sqlite-core';
export const students=sqliteTable('students',{id:text('id').primaryKey(),name:text('name').notNull(),created:text('created').notNull(),completed:text('completed'),course:text('course').notNull().default('life-stories'),snapshot:text('snapshot')},t=>[index('idx_students_course').on(t.course)]);
export const answers=sqliteTable('answers',{student:text('student').notNull().references(()=>students.id),question:integer('question').notNull(),choice:integer('choice').notNull(),correct:integer('correct').notNull()},t=>[primaryKey({columns:[t.student,t.question]})]);
export const reads=sqliteTable('reads',{student:text('student').notNull().references(()=>students.id),lesson:integer('lesson').notNull()},t=>[primaryKey({columns:[t.student,t.lesson]})]);
export const courses=sqliteTable('courses',{id:text('id').primaryKey(),title:text('title').notNull(),description:text('description').notNull(),definition:text('definition').notNull(),published:integer('published').notNull().default(0),grade:text('grade').notNull().default('general'),updated:text('updated').notNull()});

export const teacherAccount=sqliteTable('teacher_account',{id:integer('id').primaryKey(),username:text('username').notNull(),passwordHash:text('password_hash').notNull(),updated:integer('updated').notNull()});
export const teacherSessions=sqliteTable('teacher_sessions',{tokenHash:text('token_hash').primaryKey(),teacher:integer('teacher').notNull().references(()=>teacherAccount.id),created:integer('created').notNull(),expires:integer('expires').notNull()},t=>[index('idx_teacher_sessions_expires').on(t.expires)]);
export const teacherAttempts=sqliteTable('teacher_attempts',{bucket:text('bucket').primaryKey(),count:integer('count').notNull(),expires:integer('expires').notNull()});

export const teacherRecords=sqliteTable('teacher_records',{id:text('id').primaryKey(),title:text('title').notNull(),grade:text('grade').notNull(),className:text('class_name').notNull(),teacherName:text('teacher_name').notNull(),studentCount:integer('student_count').notNull(),taskCount:integer('task_count').notNull(),content:text('content').notNull(),version:integer('version').notNull().default(1),created:text('created').notNull(),updated:text('updated').notNull()});

export const studentSessions=sqliteTable('student_sessions',{student:text('student').primaryKey().references(()=>students.id),attempt:integer('attempt').notNull().default(1),started:text('started').notNull()});
export const studentAttempts=sqliteTable('student_attempts',{student:text('student').notNull().references(()=>students.id),attempt:integer('attempt').notNull(),course:text('course').notNull(),snapshot:text('snapshot').notNull(),answers:text('answers').notNull(),reads:text('reads').notNull(),score:integer('score').notNull(),total:integer('total').notNull(),answered:integer('answered').notNull(),completed:text('completed'),created:text('created').notNull()},t=>[primaryKey({columns:[t.student,t.attempt]}),index('idx_student_attempts_course').on(t.course)]);

export const studentGameRuns=sqliteTable('student_game_runs',{id:text('id').primaryKey(),student:text('student').notNull().references(()=>students.id),attempt:integer('attempt').notNull(),difficulty:text('difficulty').notNull(),rounds:text('rounds').notNull(),state:text('state').notNull(),revision:integer('revision').notNull().default(0),score:integer('score').notNull().default(0),answered:integer('answered').notNull().default(0),solved:integer('solved').notNull().default(0),status:text('status').notNull().default('playing'),created:text('created').notNull(),completed:text('completed')},t=>[index('idx_student_game_runs_attempt').on(t.student,t.attempt)]);

export const studentDictationAnswers=sqliteTable('student_dictation_answers',{student:text('student').notNull().references(()=>students.id),attempt:integer('attempt').notNull(),question:integer('question').notNull(),text:text('text').notNull(),correct:integer('correct').notNull(),created:text('created').notNull()},t=>[primaryKey({columns:[t.student,t.attempt,t.question]})]);
