import {database} from '@/lib/database';
import {hashToken,cookieName,identity} from '@/lib/student-session';
import {getCourse,originalCourse,publicCourse} from '@/lib/courses';
import type {TeacherCourse} from '@/lib/course-types';
import {answerOrder} from '@/lib/answer-order';
export const dynamic='force-dynamic';
const reply=(data:unknown,status=200,headers:Record<string,string>={})=>Response.json(data,{status,headers:{'Cache-Control':'no-store',...headers}});
const stableCourse=(c:TeacherCourse):TeacherCourse=>({id:c.id,title:c.title,description:c.description,published:1,definition:c.definition,updated:''});
async function context(req:Request,courseId:string){const c=await getCourse(courseId);if(!c)throw new Error('الدرس غير منشور أو غير موجود.');const id=await identity(req,courseId);const student=id?await database().prepare('SELECT id,name,completed,snapshot FROM students WHERE id=? AND course=?').bind(id,courseId).first<any>():null;const course:TeacherCourse=student?.snapshot?JSON.parse(student.snapshot):student&&courseId==='life-stories'?originalCourse:c;return {id,student,course:stableCourse(course),grade:c.grade||'general'};}
async function snapshot(student:any,course:TeacherCourse,grade='general'){const db=database(),id=student?.id;let answers:any[]=[],reads:any[]=[];
if(id){answers=(await db.prepare('SELECT question,choice,correct FROM answers WHERE student=? ORDER BY question').bind(id).all()).results;reads=(await db.prepare('SELECT lesson FROM reads WHERE student=?').bind(id).all()).results;}
const leaderboard=(await db.prepare('SELECT s.id,s.name,s.completed,COUNT(a.question) AS answered,COALESCE(SUM(a.correct),0) AS score FROM students s LEFT JOIN answers a ON s.id=a.student WHERE s.course=? AND COALESCE(s.snapshot,?)=? GROUP BY s.id HAVING COUNT(a.question)>0 ORDER BY score DESC,answered DESC,s.created ASC LIMIT 50').bind(course.id,JSON.stringify(stableCourse(originalCourse)),JSON.stringify(course)).all()).results;
const visible=publicCourse(course),orders=new Map<number,number[]>();
if(id)visible.questions=await Promise.all(visible.questions.map(async q=>{const order=await answerOrder(id,course.id,q.id,q.options.length);orders.set(q.id,order);return {...q,options:order.map(i=>q.options[i])};}));
return {student:student?{id:student.id,name:student.name,completed:student.completed}:null,course:{...visible,grade},answers:answers.map(a=>{const q=course.definition.questions.find(q=>q.id===a.question),order=orders.get(a.question);return {...a,choice:order?order.indexOf(a.choice):a.choice,answer:order&&q?order.indexOf(q.answer):q?.answer,reason:q?.reason,answerText:q?.options[q.answer]};}),reads:reads.map(r=>r.lesson),leaderboard};}
export async function GET(req:Request){try{const {student,course,grade}=await context(req,new URL(req.url).searchParams.get('course')||'life-stories');return reply(await snapshot(student,course,grade));}catch(e){console.error(e);return reply({error:'تعذّر تحميل الدرس والنتائج. حاول مجددًا.'},503);}}
export async function POST(req:Request){try{
if(req.headers.get('origin')&&new URL(req.headers.get('origin')!).origin!==new URL(req.url).origin)return reply({error:'طلب غير صالح.'},403);
const body=await req.json() as {course?:string;action?:string;name?:string;lesson:number;question:number;choice:number};const courseId=body.course||'life-stories';const db=database();let {id,student,course,grade}=await context(req,courseId);const {questions,lessons}=course.definition;
if(body.action==='start'){const name=typeof body.name==='string'?body.name.trim():'';if(name.length<2||name.length>60||/[<>\x00-\x1f]/.test(name))return reply({error:'أدخل اسمًا من حرفين إلى ٦٠ حرفًا.'},400);course=stableCourse((await getCourse(courseId))!);const token=crypto.randomUUID();id=await hashToken(token);const saved=JSON.stringify(course);await db.prepare('INSERT INTO students(id,name,created,course,snapshot) VALUES(?,?,?,?,?)').bind(id,name,new Date().toISOString(),courseId,saved).run();student={id,name,completed:null,snapshot:saved};return reply(await snapshot(student,course,grade),200,{'Set-Cookie':`${cookieName(courseId)}=${token}; Path=/; HttpOnly; SameSite=Lax; Max-Age=31536000${new URL(req.url).protocol==='https:'?'; Secure':''}`});}
if(!id||!student)return reply({error:'أدخل اسمك أولًا لبدء التعلم.'},401);
if(body.action==='read'){if(!Number.isInteger(body.lesson)||!lessons[body.lesson])return reply({error:'درس غير صالح.'},400);await db.prepare('INSERT OR IGNORE INTO reads(student,lesson) VALUES(?,?)').bind(id,body.lesson).run();}
else if(body.action==='answer'){const q=questions.find(q=>q.id===body.question);if(!q||!Number.isInteger(body.choice)||!q.options[body.choice])return reply({error:'إجابة غير صالحة.'},400);if(!await db.prepare('SELECT lesson FROM reads WHERE student=? AND lesson=?').bind(id,q.lesson).first())return reply({error:'أكمل قراءة شرح الدرس أولًا.'},400);const count=await db.prepare('SELECT COUNT(*) AS n FROM answers WHERE student=? AND question<?').bind(id,q.id).first<{n:number}>();if(count?.n!==questions.filter(x=>x.id<q.id).length)return reply({error:'أكمل الأسئلة بالترتيب.'},400);const order=await answerOrder(id,course.id,q.id,q.options.length),canonicalChoice=order[body.choice];await db.prepare('INSERT OR IGNORE INTO answers(student,question,choice,correct) VALUES(?,?,?,?)').bind(id,q.id,canonicalChoice,canonicalChoice===q.answer?1:0).run();}
else if(body.action==='complete'){const a=await db.prepare('SELECT COUNT(*) AS n FROM answers WHERE student=?').bind(id).first<{n:number}>();const r=await db.prepare('SELECT COUNT(*) AS n FROM reads WHERE student=?').bind(id).first<{n:number}>();if(a?.n!==questions.length||r?.n!==lessons.length)return reply({error:'أكمل جميع المحطات والأسئلة للحصول على الشهادة.'},400);await db.prepare('UPDATE students SET completed=COALESCE(completed,?) WHERE id=?').bind(new Date().toISOString(),id).run();student.completed=student.completed||new Date().toISOString();}
else return reply({error:'طلب غير صالح.'},400);
return reply(await snapshot(student,course,grade));
}catch(e){console.error(e);return reply({error:'تعذّر حفظ التقدم. حاول مجددًا.'},503);}}
